"""
Seed 50+ iconic films into the database.

Feature vector dimensions (20 total):
  0: Action       1: Drama        2: Thriller     3: Horror
  4: Comedy       5: SciFi        6: Romance      7: Crime
  8: Animation    9: Documentary
  10: pre-2000    11: 2000s       12: 2010s+
  13: avg_rating normalized (0-1, rating/10)
  14: dark        15: slow-burn   16: plot-twist  17: ensemble-cast
  18: biographical  19: foreign-language
"""

import asyncio
import json
import math
import os

import aiosqlite

import database
from database import create_tables

# Re-exported so old call sites still work, but it tracks database.DB_PATH
DB_PATH = database.DB_PATH

# fmt: off
MOVIES = [
    # ── Thrillers / Crime ──────────────────────────────────────────────────
    {
        "tmdb_id": 807, "title": "Se7en", "year": 1995,
        "director": "David Fincher", "director_id": "fincher",
        "cast": ["Brad Pitt", "Morgan Freeman", "Kevin Spacey"],
        "genres": ["Thriller", "Crime", "Drama"],
        "synopsis": "Deux détectives traquent un tueur en série s'inspirant des sept péchés capitaux.",
        "poster_url": "https://image.tmdb.org/t/p/w500/6yoghtyTpznpBik8EngEmJskVUO.jpg",
        "streaming_platforms": ["Netflix"],
        "avg_rating": 8.6,
        "is_onboarding": 1,
        # Action, Drama, Thriller, Horror, Comedy, SciFi, Romance, Crime, Anim, Doc
        # pre2k, 2000s, 2010s+, rating, dark, slow-burn, plot-twist, ensemble, bio, foreign
        "fv": [0,1,1,0, 0,0,0,1, 0,0, 1,0,0, 0.86, 1,1,1,0, 0,0],
    },
    {
        "tmdb_id": 680, "title": "Pulp Fiction", "year": 1994,
        "director": "Quentin Tarantino", "director_id": "tarantino",
        "cast": ["John Travolta", "Uma Thurman", "Samuel L. Jackson"],
        "genres": ["Crime", "Drama"],
        "synopsis": "Des histoires entrelacées de criminels à Los Angeles.",
        "poster_url": "https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
        "streaming_platforms": ["Prime Video"],
        "avg_rating": 8.9,
        "is_onboarding": 1,
        "fv": [0,1,0,0, 0,0,0,1, 0,0, 1,0,0, 0.89, 1,0,1,1, 0,0],
    },
    {
        "tmdb_id": 769, "title": "GoodFellas", "year": 1990,
        "director": "Martin Scorsese", "director_id": "scorsese",
        "cast": ["Ray Liotta", "Robert De Niro", "Joe Pesci"],
        "genres": ["Crime", "Drama"],
        "synopsis": "L'ascension et la chute d'un gangster dans la mafia new-yorkaise.",
        "poster_url": "https://image.tmdb.org/t/p/w500/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg",
        "streaming_platforms": ["Netflix"],
        "avg_rating": 8.7,
        "is_onboarding": 1,
        "fv": [0,1,0,0, 0,0,0,1, 0,0, 1,0,0, 0.87, 1,0,0,1, 0,0],
    },
    {
        "tmdb_id": 238, "title": "The Godfather", "year": 1972,
        "director": "Francis Ford Coppola", "director_id": "coppola",
        "cast": ["Marlon Brando", "Al Pacino", "James Caan"],
        "genres": ["Crime", "Drama"],
        "synopsis": "Le patriarche d'une famille de la mafia transfère le contrôle de son empire clandestin à son fils réticent.",
        "poster_url": "https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsLeFJfQ8CK2C.jpg",
        "streaming_platforms": ["Prime Video", "Paramount+"],
        "avg_rating": 9.2,
        "is_onboarding": 1,
        "fv": [0,1,0,0, 0,0,0,1, 0,0, 1,0,0, 0.92, 1,1,0,1, 0,0],
    },
    {
        "tmdb_id": 155, "title": "The Dark Knight", "year": 2008,
        "director": "Christopher Nolan", "director_id": "nolan",
        "cast": ["Christian Bale", "Heath Ledger", "Aaron Eckhart"],
        "genres": ["Action", "Drama", "Crime"],
        "synopsis": "Batman affronte le Joker, un criminel anarchiste qui sème le chaos à Gotham City.",
        "poster_url": "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
        "streaming_platforms": ["Netflix", "HBO Max"],
        "avg_rating": 9.0,
        "is_onboarding": 1,
        "fv": [1,1,0,0, 0,0,0,1, 0,0, 0,1,0, 0.90, 1,0,1,0, 0,0],
    },
    {
        "tmdb_id": 278, "title": "The Shawshank Redemption", "year": 1994,
        "director": "Frank Darabont", "director_id": "darabont",
        "cast": ["Tim Robbins", "Morgan Freeman"],
        "genres": ["Drama"],
        "synopsis": "Un banquier innocemment condamné noue une amitié profonde en prison.",
        "poster_url": "https://image.tmdb.org/t/p/w500/lyQBXzOQSuE59IsHyhrp0qIiPAz.jpg",
        "streaming_platforms": ["Netflix"],
        "avg_rating": 9.3,
        "is_onboarding": 0,
        "fv": [0,1,0,0, 0,0,0,0, 0,0, 1,0,0, 0.93, 1,1,0,0, 0,0],
    },
    {
        "tmdb_id": 550, "title": "Fight Club", "year": 1999,
        "director": "David Fincher", "director_id": "fincher",
        "cast": ["Brad Pitt", "Edward Norton", "Helena Bonham Carter"],
        "genres": ["Drama", "Thriller"],
        "synopsis": "Un cadre insatisfait fonde avec un vendeur de savon mystérieux un club de combat clandestin.",
        "poster_url": "https://image.tmdb.org/t/p/w500/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg",
        "streaming_platforms": ["Disney+"],
        "avg_rating": 8.8,
        "is_onboarding": 1,
        "fv": [0,1,1,0, 0,0,0,0, 0,0, 1,0,0, 0.88, 1,0,1,0, 0,0],
    },
    {
        "tmdb_id": 13, "title": "Forrest Gump", "year": 1994,
        "director": "Robert Zemeckis", "director_id": "zemeckis",
        "cast": ["Tom Hanks", "Robin Wright", "Gary Sinise"],
        "genres": ["Drama", "Romance"],
        "synopsis": "Les aventures d'un homme au grand cœur à travers l'histoire américaine moderne.",
        "poster_url": "https://image.tmdb.org/t/p/w500/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg",
        "streaming_platforms": ["Netflix", "Paramount+"],
        "avg_rating": 8.8,
        "is_onboarding": 0,
        "fv": [0,1,0,0, 0,0,1,0, 0,0, 1,0,0, 0.88, 0,0,0,0, 0,0],
    },
    # ── Sci-Fi ────────────────────────────────────────────────────────────
    {
        "tmdb_id": 157336, "title": "Interstellar", "year": 2014,
        "director": "Christopher Nolan", "director_id": "nolan",
        "cast": ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain"],
        "genres": ["SciFi", "Drama"],
        "synopsis": "Un groupe d'explorateurs voyage à travers un trou de ver pour assurer la survie de l'humanité.",
        "poster_url": "https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
        "streaming_platforms": ["Netflix", "Prime Video"],
        "avg_rating": 8.6,
        "is_onboarding": 1,
        "fv": [0,1,0,0, 0,1,0,0, 0,0, 0,0,1, 0.86, 0,1,1,0, 0,0],
    },
    {
        "tmdb_id": 27205, "title": "Inception", "year": 2010,
        "director": "Christopher Nolan", "director_id": "nolan",
        "cast": ["Leonardo DiCaprio", "Joseph Gordon-Levitt", "Elliot Page"],
        "genres": ["SciFi", "Action", "Thriller"],
        "synopsis": "Un voleur qui s'infiltre dans les rêves se voit offrir la chance d'effacer son passé.",
        "poster_url": "https://image.tmdb.org/t/p/w500/edv5CZvWj09upOsy2Y6IwDhK8bt.jpg",
        "streaming_platforms": ["Netflix", "HBO Max"],
        "avg_rating": 8.8,
        "is_onboarding": 0,
        "fv": [1,0,1,0, 0,1,0,0, 0,0, 0,1,0, 0.88, 0,0,1,1, 0,0],
    },
    {
        "tmdb_id": 603, "title": "The Matrix", "year": 1999,
        "director": "Lana Wachowski", "director_id": "wachowski",
        "cast": ["Keanu Reeves", "Laurence Fishburne", "Carrie-Anne Moss"],
        "genres": ["SciFi", "Action"],
        "synopsis": "Un hacker découvre que la réalité telle qu'il la connaît est une simulation.",
        "poster_url": "https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg",
        "streaming_platforms": ["Netflix", "HBO Max"],
        "avg_rating": 8.7,
        "is_onboarding": 0,
        "fv": [1,0,0,0, 0,1,0,0, 0,0, 1,0,0, 0.87, 1,0,1,0, 0,0],
    },
    {
        "tmdb_id": 862, "title": "Toy Story", "year": 1995,
        "director": "John Lasseter", "director_id": "lasseter",
        "cast": ["Tom Hanks", "Tim Allen"],
        "genres": ["Animation", "Comedy"],
        "synopsis": "Les jouets d'un enfant prennent vie et vivent leurs propres aventures.",
        "poster_url": "https://image.tmdb.org/t/p/w500/uXDfjJbdP4ijW5hWSBrPivLqxyd.jpg",
        "streaming_platforms": ["Disney+"],
        "avg_rating": 8.3,
        "is_onboarding": 0,
        "fv": [0,0,0,0, 1,0,0,0, 1,0, 1,0,0, 0.83, 0,0,0,0, 0,0],
    },
    {
        "tmdb_id": 424, "title": "Schindler's List", "year": 1993,
        "director": "Steven Spielberg", "director_id": "spielberg",
        "cast": ["Liam Neeson", "Ben Kingsley", "Ralph Fiennes"],
        "genres": ["Drama", "History"],
        "synopsis": "Un industriel allemand sauve plus d'un millier de Juifs polonais de l'Holocauste.",
        "poster_url": "https://image.tmdb.org/t/p/w500/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg",
        "streaming_platforms": ["Prime Video"],
        "avg_rating": 9.0,
        "is_onboarding": 0,
        "fv": [0,1,0,0, 0,0,0,0, 0,0, 1,0,0, 0.90, 1,1,0,0, 1,0],
    },
    # ── Horror ────────────────────────────────────────────────────────────
    {
        "tmdb_id": 694, "title": "The Shining", "year": 1980,
        "director": "Stanley Kubrick", "director_id": "kubrick",
        "cast": ["Jack Nicholson", "Shelley Duvall"],
        "genres": ["Horror", "Drama"],
        "synopsis": "Un écrivain s'installe comme gardien d'un hôtel isolé avec sa famille, et sombre dans la folie.",
        "poster_url": "https://image.tmdb.org/t/p/w500/nRj5511mZdTl4saWEPoj9QroTIu.jpg",
        "streaming_platforms": ["HBO Max"],
        "avg_rating": 8.4,
        "is_onboarding": 1,
        "fv": [0,0,0,1, 0,0,0,0, 0,0, 1,0,0, 0.84, 1,1,0,0, 0,0],
    },
    {
        "tmdb_id": 539, "title": "Psycho", "year": 1960,
        "director": "Alfred Hitchcock", "director_id": "hitchcock",
        "cast": ["Anthony Perkins", "Janet Leigh"],
        "genres": ["Horror", "Thriller"],
        "synopsis": "Une secrétaire en fuite s'arrête dans un motel isolé tenu par un étrange jeune homme.",
        "poster_url": "https://image.tmdb.org/t/p/w500/yz4QVqPx3h8hVSdMCd7ixNubCfv.jpg",
        "streaming_platforms": ["Peacock"],
        "avg_rating": 8.5,
        "is_onboarding": 0,
        "fv": [0,0,1,1, 0,0,0,0, 0,0, 1,0,0, 0.85, 1,0,1,0, 0,0],
    },
    {
        "tmdb_id": 346648, "title": "Hereditary", "year": 2018,
        "director": "Ari Aster", "director_id": "aster",
        "cast": ["Toni Collette", "Alex Wolff", "Gabriel Byrne"],
        "genres": ["Horror", "Drama"],
        "synopsis": "Une famille endeuillée découvre des secrets terrifiants liés à leur passé.",
        "poster_url": "https://image.tmdb.org/t/p/w500/4O1sPouIJBSTBqXJSyCqaxMd9Zw.jpg",
        "streaming_platforms": ["Prime Video"],
        "avg_rating": 7.3,
        "is_onboarding": 0,
        "fv": [0,1,0,1, 0,0,0,0, 0,0, 0,0,1, 0.73, 1,1,1,0, 0,0],
    },
    {
        "tmdb_id": 496243, "title": "Parasite", "year": 2019,
        "director": "Bong Joon-ho", "director_id": "bong",
        "cast": ["Kang-ho Song", "Sun-kyun Lee", "Yeo-jeong Jo"],
        "genres": ["Drama", "Thriller", "Crime"],
        "synopsis": "La famille Kim s'infiltre dans la vie de la riche famille Park.",
        "poster_url": "https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
        "streaming_platforms": ["Mubi"],
        "avg_rating": 8.5,
        "is_onboarding": 1,
        "fv": [0,1,1,0, 0,0,0,1, 0,0, 0,0,1, 0.85, 1,0,1,1, 0,1],
    },
    # ── Drama ─────────────────────────────────────────────────────────────
    {
        "tmdb_id": 264644, "title": "Room", "year": 2015,
        "director": "Lenny Abrahamson", "director_id": "abrahamson",
        "cast": ["Brie Larson", "Jacob Tremblay"],
        "genres": ["Drama", "Thriller"],
        "synopsis": "Une mère et son fils tentent de s'adapter après avoir été libérés d'une captivité.",
        "poster_url": "https://image.tmdb.org/t/p/w500/bOp0zKzsBJZKIHNhRVW0t2NxHSY.jpg",
        "streaming_platforms": ["Netflix"],
        "avg_rating": 8.1,
        "is_onboarding": 0,
        "fv": [0,1,1,0, 0,0,0,0, 0,0, 0,0,1, 0.81, 1,1,0,0, 0,0],
    },
    {
        "tmdb_id": 244786, "title": "Whiplash", "year": 2014,
        "director": "Damien Chazelle", "director_id": "chazelle",
        "cast": ["Miles Teller", "J.K. Simmons"],
        "genres": ["Drama", "Music"],
        "synopsis": "Un jeune batteur de jazz ambitieux est poussé à ses limites par un professeur tyrannique.",
        "poster_url": "https://image.tmdb.org/t/p/w500/7fn624j5lj3xTme2SgiLCeuedmO.jpg",
        "streaming_platforms": ["Netflix", "Prime Video"],
        "avg_rating": 8.5,
        "is_onboarding": 0,
        "fv": [0,1,0,0, 0,0,0,0, 0,0, 0,0,1, 0.85, 1,0,0,0, 0,0],
    },
    {
        "tmdb_id": 361743, "title": "Top Gun: Maverick", "year": 2022,
        "director": "Joseph Kosinski", "director_id": "kosinski",
        "cast": ["Tom Cruise", "Miles Teller", "Jennifer Connelly"],
        "genres": ["Action", "Drama"],
        "synopsis": "Maverick affronte ses démons tout en entraînant une nouvelle génération de pilotes.",
        "poster_url": "https://image.tmdb.org/t/p/w500/62HCnUTziyWcpDaBO2i1DX17ljH.jpg",
        "streaming_platforms": ["Paramount+", "Prime Video"],
        "avg_rating": 8.3,
        "is_onboarding": 0,
        "fv": [1,1,0,0, 0,0,0,0, 0,0, 0,0,1, 0.83, 0,0,0,0, 0,0],
    },
    {
        "tmdb_id": 120467, "title": "The Grand Budapest Hotel", "year": 2014,
        "director": "Wes Anderson", "director_id": "anderson_w",
        "cast": ["Ralph Fiennes", "Tony Revolori", "Saoirse Ronan"],
        "genres": ["Comedy", "Drama"],
        "synopsis": "Les aventures d'un concierge légendaire et de son jeune protégé dans un hôtel de luxe.",
        "poster_url": "https://image.tmdb.org/t/p/w500/eWdyYQreja6JGCzqHWXpWHDrrPo.jpg",
        "streaming_platforms": ["Disney+", "HBO Max"],
        "avg_rating": 8.1,
        "is_onboarding": 0,
        "fv": [0,1,0,0, 1,0,0,1, 0,0, 0,0,1, 0.81, 0,0,0,1, 0,0],
    },
    {
        "tmdb_id": 77338, "title": "The Artist", "year": 2011,
        "director": "Michel Hazanavicius", "director_id": "hazanavicius",
        "cast": ["Jean Dujardin", "Bérénice Bejo"],
        "genres": ["Comedy", "Drama", "Romance"],
        "synopsis": "Un acteur du muet voit sa carrière s'effondrer avec l'avènement du cinéma parlant.",
        "poster_url": "https://image.tmdb.org/t/p/w500/gTOAiP3eRhXGqxZwFcGhSDmSBYb.jpg",
        "streaming_platforms": ["Mubi"],
        "avg_rating": 7.9,
        "is_onboarding": 0,
        "fv": [0,1,0,0, 1,0,1,0, 0,0, 0,1,0, 0.79, 0,0,0,0, 0,1],
    },
    {
        "tmdb_id": 637, "title": "Life Is Beautiful", "year": 1997,
        "director": "Roberto Benigni", "director_id": "benigni",
        "cast": ["Roberto Benigni", "Nicoletta Braschi"],
        "genres": ["Drama", "Comedy", "Romance"],
        "synopsis": "Un père juif en Italie fasciste tente de protéger son fils dans un camp de concentration.",
        "poster_url": "https://image.tmdb.org/t/p/w500/74hLDKjD5aGYOotO6esUVaeISa2.jpg",
        "streaming_platforms": ["Netflix"],
        "avg_rating": 8.6,
        "is_onboarding": 0,
        "fv": [0,1,0,0, 1,0,1,0, 0,0, 1,0,0, 0.86, 1,0,0,0, 0,1],
    },
    # ── Action / Adventure ────────────────────────────────────────────────
    {
        "tmdb_id": 19404, "title": "Dilwale Dulhania Le Jayenge", "year": 1995,
        "director": "Aditya Chopra", "director_id": "chopra",
        "cast": ["Shah Rukh Khan", "Kajol"],
        "genres": ["Romance", "Drama"],
        "synopsis": "Deux jeunes Indiens de la diaspora tombent amoureux lors d'un voyage en Europe.",
        "poster_url": "https://image.tmdb.org/t/p/w500/2CAL2433ZeIihfX1Hb2139CX0pW.jpg",
        "streaming_platforms": ["Netflix"],
        "avg_rating": 8.1,
        "is_onboarding": 0,
        "fv": [0,1,0,0, 0,0,1,0, 0,0, 1,0,0, 0.81, 0,0,0,0, 0,1],
    },
    {
        "tmdb_id": 120, "title": "The Lord of the Rings: The Fellowship of the Ring", "year": 2001,
        "director": "Peter Jackson", "director_id": "jackson",
        "cast": ["Elijah Wood", "Ian McKellen", "Viggo Mortensen"],
        "genres": ["Action", "Drama", "Fantasy"],
        "synopsis": "Un jeune hobbit entreprend un voyage périlleux pour détruire un anneau maléfique.",
        "poster_url": "https://image.tmdb.org/t/p/w500/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg",
        "streaming_platforms": ["HBO Max"],
        "avg_rating": 8.8,
        "is_onboarding": 0,
        "fv": [1,1,0,0, 0,0,0,0, 0,0, 0,1,0, 0.88, 0,0,0,1, 0,0],
    },
    {
        "tmdb_id": 13916, "title": "Inglourious Basterds", "year": 2009,
        "director": "Quentin Tarantino", "director_id": "tarantino",
        "cast": ["Brad Pitt", "Christoph Waltz", "Mélanie Laurent"],
        "genres": ["Drama", "Action", "War"],
        "synopsis": "Plusieurs complots convergent pour assassiner Adolf Hitler dans la France occupée.",
        "poster_url": "https://image.tmdb.org/t/p/w500/7sfbEnaARXDDhKm0CZ7D7uc2sbo.jpg",
        "streaming_platforms": ["Netflix"],
        "avg_rating": 8.3,
        "is_onboarding": 0,
        "fv": [1,1,0,0, 0,0,0,0, 0,0, 0,1,0, 0.83, 1,0,1,1, 0,0],
    },
    {
        "tmdb_id": 101, "title": "Leon: The Professional", "year": 1994,
        "director": "Luc Besson", "director_id": "besson",
        "cast": ["Jean Reno", "Natalie Portman", "Gary Oldman"],
        "genres": ["Action", "Crime", "Drama"],
        "synopsis": "Un tueur à gages solitaire recueille une jeune fille dont la famille a été assassinée.",
        "poster_url": "https://image.tmdb.org/t/p/w500/yI6X2cCM5YPJtxMhUd3dPGqDAhw.jpg",
        "streaming_platforms": ["Prime Video"],
        "avg_rating": 8.5,
        "is_onboarding": 0,
        "fv": [1,1,0,0, 0,0,0,1, 0,0, 1,0,0, 0.85, 1,0,0,0, 0,1],
    },
    # ── Comedy ────────────────────────────────────────────────────────────
    {
        "tmdb_id": 19, "title": "Amélie", "year": 2001,
        "director": "Jean-Pierre Jeunet", "director_id": "jeunet",
        "cast": ["Audrey Tautou", "Mathieu Kassovitz"],
        "genres": ["Comedy", "Romance"],
        "synopsis": "Une jeune femme rêveuse décide d'améliorer la vie des gens qui l'entourent.",
        "poster_url": "https://image.tmdb.org/t/p/w500/mMtucybCbBemqta6OLe0G8gv0Ww.jpg",
        "streaming_platforms": ["Mubi", "Prime Video"],
        "avg_rating": 8.3,
        "is_onboarding": 0,
        "fv": [0,0,0,0, 1,0,1,0, 0,0, 0,1,0, 0.83, 0,0,0,0, 0,1],
    },
    {
        "tmdb_id": 68718, "title": "Django Unchained", "year": 2012,
        "director": "Quentin Tarantino", "director_id": "tarantino",
        "cast": ["Jamie Foxx", "Christoph Waltz", "Leonardo DiCaprio"],
        "genres": ["Drama", "Action", "Western"],
        "synopsis": "Un esclave affranchi et un chasseur de primes partent à la recherche de la femme de l'un d'eux.",
        "poster_url": "https://image.tmdb.org/t/p/w500/7oWY8VDWW7thTzWh3OKYRkWUlD5.jpg",
        "streaming_platforms": ["Netflix"],
        "avg_rating": 8.4,
        "is_onboarding": 0,
        "fv": [1,1,0,0, 0,0,0,0, 0,0, 0,0,1, 0.84, 1,0,0,0, 0,0],
    },
    {
        "tmdb_id": 1817, "title": "There Will Be Blood", "year": 2007,
        "director": "Paul Thomas Anderson", "director_id": "pta",
        "cast": ["Daniel Day-Lewis", "Paul Dano"],
        "genres": ["Drama"],
        "synopsis": "L'ascension d'un prospecteur pétrolier implacable dans la Californie du début du XXe siècle.",
        "poster_url": "https://image.tmdb.org/t/p/w500/fa0RDkAlCec0STeMNAhPaF89q6U.jpg",
        "streaming_platforms": ["Mubi"],
        "avg_rating": 8.2,
        "is_onboarding": 0,
        "fv": [0,1,0,0, 0,0,0,0, 0,0, 0,1,0, 0.82, 1,1,0,0, 0,0],
    },
    {
        "tmdb_id": 489, "title": "Good Will Hunting", "year": 1997,
        "director": "Gus Van Sant", "director_id": "vansant",
        "cast": ["Matt Damon", "Robin Williams", "Ben Affleck"],
        "genres": ["Drama", "Romance"],
        "synopsis": "Un jeune génie travaillant comme concierge du MIT est aidé par un psychologue compatissant.",
        "poster_url": "https://image.tmdb.org/t/p/w500/bABCBKYBK7A5G1x0FzoeoNfuj2.jpg",
        "streaming_platforms": ["Netflix"],
        "avg_rating": 8.3,
        "is_onboarding": 0,
        "fv": [0,1,0,0, 0,0,1,0, 0,0, 1,0,0, 0.83, 0,0,0,0, 0,0],
    },
    {
        "tmdb_id": 566525, "title": "Shang-Chi and the Legend of the Ten Rings", "year": 2021,
        "director": "Destin Daniel Cretton", "director_id": "cretton",
        "cast": ["Simu Liu", "Tony Leung", "Awkwafina"],
        "genres": ["Action", "Fantasy"],
        "synopsis": "Un homme est entraîné dans le monde de la Ten Rings, une organisation secrète.",
        "poster_url": "https://image.tmdb.org/t/p/w500/1BIoJGKbXjdFDAqUEiA2VHqkK1Z.jpg",
        "streaming_platforms": ["Disney+"],
        "avg_rating": 7.4,
        "is_onboarding": 0,
        "fv": [1,0,0,0, 0,0,0,0, 0,0, 0,0,1, 0.74, 0,0,0,0, 0,0],
    },
    {
        "tmdb_id": 724089, "title": "Gabriel's Inferno", "year": 2020,
        "director": "Tosca Musk", "director_id": "musk_t",
        "cast": ["Giulio Berruti", "Melanie Zanetti"],
        "genres": ["Romance", "Drama"],
        "synopsis": "Un professeur de Dante et son étudiante vivent une histoire d'amour interdite.",
        "poster_url": "https://image.tmdb.org/t/p/w500/oyG9TL7FcRP4EZ9Vid6uKzwdndz.jpg",
        "streaming_platforms": ["Prime Video"],
        "avg_rating": 7.0,
        "is_onboarding": 0,
        "fv": [0,1,0,0, 0,0,1,0, 0,0, 0,0,1, 0.70, 0,0,0,0, 0,0],
    },
    # ── Foreign / Art House ───────────────────────────────────────────────
    {
        "tmdb_id": 129, "title": "Spirited Away", "year": 2001,
        "director": "Hayao Miyazaki", "director_id": "miyazaki",
        "cast": ["Daveigh Chase", "Suzanne Pleshette"],
        "genres": ["Animation", "Fantasy", "Drama"],
        "synopsis": "Une jeune fille est entraînée dans un monde fantastique après que ses parents sont transformés en cochons.",
        "poster_url": "https://image.tmdb.org/t/p/w500/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg",
        "streaming_platforms": ["Netflix"],
        "avg_rating": 8.6,
        "is_onboarding": 0,
        "fv": [0,1,0,0, 0,0,0,0, 1,0, 0,1,0, 0.86, 0,0,0,0, 0,1],
    },
    {
        "tmdb_id": 429617, "title": "Spider-Man: Into the Spider-Verse", "year": 2018,
        "director": "Bob Persichetti", "director_id": "persichetti",
        "cast": ["Shameik Moore", "Jake Johnson"],
        "genres": ["Animation", "Action", "SciFi"],
        "synopsis": "Miles Morales devient Spider-Man et rencontre des Spider-Men d'autres dimensions.",
        "poster_url": "https://image.tmdb.org/t/p/w500/iiZZdoQBEYBv6id8su7ImL0oCbD.jpg",
        "streaming_platforms": ["Netflix"],
        "avg_rating": 8.4,
        "is_onboarding": 0,
        "fv": [1,0,0,0, 0,1,0,0, 1,0, 0,0,1, 0.84, 0,0,1,1, 0,0],
    },
    {
        "tmdb_id": 508442, "title": "Soul", "year": 2020,
        "director": "Pete Docter", "director_id": "docter",
        "cast": ["Jamie Foxx", "Tina Fey"],
        "genres": ["Animation", "Comedy", "Drama"],
        "synopsis": "Un musicien de jazz se retrouve dans le monde des âmes avant de naître.",
        "poster_url": "https://image.tmdb.org/t/p/w500/hm58Jw4Lw8OIeECIq5qyPYhAeRJ.jpg",
        "streaming_platforms": ["Disney+"],
        "avg_rating": 8.1,
        "is_onboarding": 0,
        "fv": [0,1,0,0, 1,0,0,0, 1,0, 0,0,1, 0.81, 0,0,1,0, 0,0],
    },
    {
        "tmdb_id": 264660, "title": "Ex Machina", "year": 2014,
        "director": "Alex Garland", "director_id": "garland",
        "cast": ["Domhnall Gleeson", "Alicia Vikander", "Oscar Isaac"],
        "genres": ["SciFi", "Thriller", "Drama"],
        "synopsis": "Un programmeur est sélectionné pour évaluer les capacités d'une IA à forme humaine.",
        "poster_url": "https://image.tmdb.org/t/p/w500/btpFaZFg3bwzKzGqOuGlCDtN8Gg.jpg",
        "streaming_platforms": ["Prime Video", "Netflix"],
        "avg_rating": 7.7,
        "is_onboarding": 0,
        "fv": [0,1,1,0, 0,1,0,0, 0,0, 0,0,1, 0.77, 1,1,1,0, 0,0],
    },
    {
        "tmdb_id": 299536, "title": "Avengers: Infinity War", "year": 2018,
        "director": "Anthony Russo", "director_id": "russo_a",
        "cast": ["Robert Downey Jr.", "Chris Evans", "Josh Brolin"],
        "genres": ["Action", "SciFi"],
        "synopsis": "Les Avengers s'unissent pour empêcher Thanos de rassembler les Pierres de l'Infini.",
        "poster_url": "https://image.tmdb.org/t/p/w500/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg",
        "streaming_platforms": ["Disney+"],
        "avg_rating": 8.4,
        "is_onboarding": 0,
        "fv": [1,0,0,0, 0,1,0,0, 0,0, 0,0,1, 0.84, 1,0,1,1, 0,0],
    },
    {
        "tmdb_id": 313369, "title": "La La Land", "year": 2016,
        "director": "Damien Chazelle", "director_id": "chazelle",
        "cast": ["Ryan Gosling", "Emma Stone"],
        "genres": ["Drama", "Romance", "Music"],
        "synopsis": "Un pianiste de jazz et une aspirante actrice tombent amoureux à Los Angeles.",
        "poster_url": "https://image.tmdb.org/t/p/w500/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg",
        "streaming_platforms": ["Netflix"],
        "avg_rating": 8.0,
        "is_onboarding": 0,
        "fv": [0,1,0,0, 0,0,1,0, 0,0, 0,0,1, 0.80, 0,0,0,0, 0,0],
    },
    {
        "tmdb_id": 475557, "title": "Joker", "year": 2019,
        "director": "Todd Phillips", "director_id": "phillips",
        "cast": ["Joaquin Phoenix", "Robert De Niro"],
        "genres": ["Crime", "Drama", "Thriller"],
        "synopsis": "L'origine d'Arthur Fleck, un comédien raté qui sombre dans la folie et devient le Joker.",
        "poster_url": "https://image.tmdb.org/t/p/w500/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg",
        "streaming_platforms": ["HBO Max"],
        "avg_rating": 8.4,
        "is_onboarding": 0,
        "fv": [0,1,1,0, 0,0,0,1, 0,0, 0,0,1, 0.84, 1,1,0,0, 1,0],
    },
    {
        "tmdb_id": 901362, "title": "Trolls Band Together", "year": 2023,
        "director": "Walt Dohrn", "director_id": "dohrn",
        "cast": ["Anna Kendrick", "Justin Timberlake"],
        "genres": ["Animation", "Comedy", "Music"],
        "synopsis": "Poppy aide Branch à retrouver ses frères boy band pour sauver leur petite sœur.",
        "poster_url": "https://image.tmdb.org/t/p/w500/bkpPTZUdq31UGDovmszsg2CchiI.jpg",
        "streaming_platforms": ["Netflix", "Peacock"],
        "avg_rating": 5.9,
        "is_onboarding": 0,
        "fv": [0,0,0,0, 1,0,0,0, 1,0, 0,0,1, 0.59, 0,0,0,0, 0,0],
    },
    {
        "tmdb_id": 346, "title": "Seven Samurai", "year": 1954,
        "director": "Akira Kurosawa", "director_id": "kurosawa",
        "cast": ["Toshiro Mifune", "Takashi Shimura"],
        "genres": ["Action", "Drama"],
        "synopsis": "Un village de paysans engage sept samouraïs pour les protéger contre des bandits.",
        "poster_url": "https://image.tmdb.org/t/p/w500/8OKmBV5BUFzmozIC3pPWKHy17kx.jpg",
        "streaming_platforms": ["Criterion", "Mubi"],
        "avg_rating": 8.7,
        "is_onboarding": 0,
        "fv": [1,1,0,0, 0,0,0,0, 0,0, 1,0,0, 0.87, 0,1,0,1, 0,1],
    },
    {
        "tmdb_id": 240, "title": "The Godfather Part II", "year": 1974,
        "director": "Francis Ford Coppola", "director_id": "coppola",
        "cast": ["Al Pacino", "Robert De Niro", "Robert Duvall"],
        "genres": ["Crime", "Drama"],
        "synopsis": "L'empire de Michael Corleone s'étend alors que des flashbacks montrent la jeunesse de Vito.",
        "poster_url": "https://image.tmdb.org/t/p/w500/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg",
        "streaming_platforms": ["Prime Video", "Paramount+"],
        "avg_rating": 9.0,
        "is_onboarding": 0,
        "fv": [0,1,0,0, 0,0,0,1, 0,0, 1,0,0, 0.90, 1,1,0,1, 0,0],
    },
    {
        "tmdb_id": 598, "title": "City of God", "year": 2002,
        "director": "Fernando Meirelles", "director_id": "meirelles",
        "cast": ["Alexandre Rodrigues", "Leandro Firmino"],
        "genres": ["Crime", "Drama"],
        "synopsis": "Deux jeunes hommes grandissent dans les favelas de Rio de Janeiro des années 60-80.",
        "poster_url": "https://image.tmdb.org/t/p/w500/k7eYdWvhYQyRQoU2TB2A2Xu2grZ.jpg",
        "streaming_platforms": ["Netflix"],
        "avg_rating": 8.6,
        "is_onboarding": 0,
        "fv": [0,1,0,0, 0,0,0,1, 0,0, 0,1,0, 0.86, 1,0,0,0, 0,1],
    },
    {
        "tmdb_id": 762, "title": "Monty Python and the Holy Grail", "year": 1975,
        "director": "Terry Gilliam", "director_id": "gilliam",
        "cast": ["Graham Chapman", "John Cleese", "Terry Gilliam"],
        "genres": ["Comedy"],
        "synopsis": "Le Roi Arthur et ses chevaliers partent en quête du Saint Graal.",
        "poster_url": "https://image.tmdb.org/t/p/w500/sGyllguekBSFqpUMhtpFkDpNYmQ.jpg",
        "streaming_platforms": ["Netflix"],
        "avg_rating": 8.2,
        "is_onboarding": 0,
        "fv": [0,0,0,0, 1,0,0,0, 0,0, 1,0,0, 0.82, 0,0,0,1, 0,0],
    },
    {
        "tmdb_id": 37724, "title": "Skyfall", "year": 2012,
        "director": "Sam Mendes", "director_id": "mendes",
        "cast": ["Daniel Craig", "Judi Dench", "Javier Bardem"],
        "genres": ["Action", "Thriller"],
        "synopsis": "James Bond affronte un ancien agent du MI6 qui cherche à se venger.",
        "poster_url": "https://image.tmdb.org/t/p/w500/dyFGMzCNY1vE8I3S5qFrLjBqGq4.jpg",
        "streaming_platforms": ["Netflix", "Prime Video"],
        "avg_rating": 7.8,
        "is_onboarding": 0,
        "fv": [1,0,1,0, 0,0,0,0, 0,0, 0,0,1, 0.78, 0,0,1,0, 0,0],
    },
    {
        "tmdb_id": 280, "title": "Terminator 2: Judgment Day", "year": 1991,
        "director": "James Cameron", "director_id": "cameron",
        "cast": ["Arnold Schwarzenegger", "Linda Hamilton", "Edward Furlong"],
        "genres": ["Action", "SciFi"],
        "synopsis": "Un Terminator reprogrammé protège le jeune John Connor d'un robot du futur plus avancé.",
        "poster_url": "https://image.tmdb.org/t/p/w500/5M0j0B18abtBI5gi2RhfjjurTqb.jpg",
        "streaming_platforms": ["Netflix"],
        "avg_rating": 8.6,
        "is_onboarding": 0,
        "fv": [1,0,0,0, 0,1,0,0, 0,0, 1,0,0, 0.86, 1,0,1,0, 0,0],
    },
    {
        "tmdb_id": 11, "title": "Star Wars: A New Hope", "year": 1977,
        "director": "George Lucas", "director_id": "lucas",
        "cast": ["Mark Hamill", "Harrison Ford", "Carrie Fisher"],
        "genres": ["Action", "SciFi", "Fantasy"],
        "synopsis": "Un jeune fermier rejoint la Rébellion galactique contre l'Empire tyrannique.",
        "poster_url": "https://image.tmdb.org/t/p/w500/6FfCtAuVAW8XJjZ7eWeLibRLWTw.jpg",
        "streaming_platforms": ["Disney+"],
        "avg_rating": 8.6,
        "is_onboarding": 0,
        "fv": [1,0,0,0, 0,1,0,0, 0,0, 1,0,0, 0.86, 0,0,0,1, 0,0],
    },
    {
        "tmdb_id": 23272, "title": "Into the Wild", "year": 2007,
        "director": "Sean Penn", "director_id": "penn",
        "cast": ["Emile Hirsch", "Marcia Gay Harden", "William Hurt"],
        "genres": ["Drama", "Adventure"],
        "synopsis": "Après avoir donné ses économies à une association, un jeune diplômé part seul en Alaska.",
        "poster_url": "https://image.tmdb.org/t/p/w500/wBthfNBLQOC3szVKPYsemysPFJv.jpg",
        "streaming_platforms": ["Netflix"],
        "avg_rating": 8.1,
        "is_onboarding": 0,
        "fv": [0,1,0,0, 0,0,0,0, 0,0, 0,1,0, 0.81, 0,1,0,0, 1,0],
    },
    {
        "tmdb_id": 372058, "title": "Your Name", "year": 2016,
        "director": "Makoto Shinkai", "director_id": "shinkai",
        "cast": ["Ryunosuke Kamiki", "Mone Kamishiraishi"],
        "genres": ["Animation", "Drama", "Romance"],
        "synopsis": "Deux lycéens se retrouvent mystérieusement à échanger leurs corps.",
        "poster_url": "https://image.tmdb.org/t/p/w500/q719jXXEzOoYaps6babgKnONONX.jpg",
        "streaming_platforms": ["Netflix"],
        "avg_rating": 8.4,
        "is_onboarding": 0,
        "fv": [0,1,0,0, 0,0,1,0, 1,0, 0,0,1, 0.84, 0,0,1,0, 0,1],
    },
    {
        "tmdb_id": 598650, "title": "The Batman", "year": 2022,
        "director": "Matt Reeves", "director_id": "reeves",
        "cast": ["Robert Pattinson", "Zoë Kravitz", "Paul Dano"],
        "genres": ["Action", "Crime", "Thriller"],
        "synopsis": "Batman démasque la corruption de Gotham alors qu'il pourchasse un tueur en série.",
        "poster_url": "https://image.tmdb.org/t/p/w500/74xTEgt7R36Fpooo50r9T25onhq.jpg",
        "streaming_platforms": ["HBO Max"],
        "avg_rating": 7.8,
        "is_onboarding": 0,
        "fv": [1,0,1,0, 0,0,0,1, 0,0, 0,0,1, 0.78, 1,1,1,0, 0,0],
    },
    {
        "tmdb_id": 539681, "title": "Oppenheimer", "year": 2023,
        "director": "Christopher Nolan", "director_id": "nolan",
        "cast": ["Cillian Murphy", "Emily Blunt", "Matt Damon"],
        "genres": ["Drama", "History"],
        "synopsis": "La vie du physicien J. Robert Oppenheimer qui a dirigé le Projet Manhattan.",
        "poster_url": "https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
        "streaming_platforms": ["Peacock"],
        "avg_rating": 8.3,
        "is_onboarding": 0,
        "fv": [0,1,0,0, 0,0,0,0, 0,0, 0,0,1, 0.83, 1,1,0,1, 1,0],
    },
    {
        "tmdb_id": 545611, "title": "Everything Everywhere All at Once", "year": 2022,
        "director": "Daniel Kwan", "director_id": "daniels",
        "cast": ["Michelle Yeoh", "Stephanie Hsu", "Ke Huy Quan"],
        "genres": ["SciFi", "Comedy", "Drama"],
        "synopsis": "Une femme découvre qu'elle seule peut sauver le multivers en explorant d'autres vies.",
        "poster_url": "https://image.tmdb.org/t/p/w500/w3LxiVYdWWRvEVdn5RYq6jIqkb1.jpg",
        "streaming_platforms": ["Prime Video", "Mubi"],
        "avg_rating": 7.8,
        "is_onboarding": 0,
        "fv": [0,1,0,0, 1,1,0,0, 0,0, 0,0,1, 0.78, 0,0,1,0, 0,0],
    },
    {
        "tmdb_id": 76341, "title": "Mad Max: Fury Road", "year": 2015,
        "director": "George Miller", "director_id": "miller_g",
        "cast": ["Tom Hardy", "Charlize Theron", "Nicholas Hoult"],
        "genres": ["Action", "SciFi"],
        "synopsis": "Dans un désert post-apocalyptique, Max aide Furiosa à libérer des esclaves.",
        "poster_url": "https://image.tmdb.org/t/p/w500/8tZYtuWezp8JbcsvHYO0O46tFbo.jpg",
        "streaming_platforms": ["Netflix", "HBO Max"],
        "avg_rating": 8.1,
        "is_onboarding": 0,
        "fv": [1,0,0,0, 0,1,0,0, 0,0, 0,0,1, 0.81, 1,0,0,0, 0,0],
    },
    # ── Thrillers supplémentaires ──────────────────────────────────────────
    {
        "tmdb_id": 77, "title": "Memento", "year": 2000,
        "director": "Christopher Nolan", "director_id": "nolan",
        "cast": ["Guy Pearce", "Carrie-Anne Moss", "Joe Pantoliano"],
        "genres": ["Thriller", "Drama"],
        "synopsis": "Un homme atteint d'amnésie à court terme tente de retrouver le meurtrier de sa femme.",
        "poster_url": "https://image.tmdb.org/t/p/w500/yuNs09hvpHVU1cBTCAk9zxsL2oW.jpg",
        "streaming_platforms": ["Netflix"],
        "avg_rating": 8.4,
        "is_onboarding": 0,
        "fv": [0,1,1,0, 0,0,0,0, 0,0, 0,1,0, 0.84, 1,0,1,0, 0,0],
    },
    {
        "tmdb_id": 274, "title": "The Silence of the Lambs", "year": 1991,
        "director": "Jonathan Demme", "director_id": "demme",
        "cast": ["Jodie Foster", "Anthony Hopkins", "Scott Glenn"],
        "genres": ["Thriller", "Crime", "Drama"],
        "synopsis": "Une jeune agent du FBI doit faire appel à un brillant psychiatre cannibale pour attraper un tueur en série.",
        "poster_url": "https://image.tmdb.org/t/p/w500/uS9m8OBk1A8eM9I042bx8XXEhit.jpg",
        "streaming_platforms": ["Prime Video"],
        "avg_rating": 8.6,
        "is_onboarding": 0,
        "fv": [0,1,1,0, 0,0,0,1, 0,0, 1,0,0, 0.86, 1,1,0,0, 0,0],
    },
    {
        "tmdb_id": 6977, "title": "No Country for Old Men", "year": 2007,
        "director": "Joel Coen", "director_id": "coen",
        "cast": ["Tommy Lee Jones", "Javier Bardem", "Josh Brolin"],
        "genres": ["Thriller", "Crime", "Drama"],
        "synopsis": "Un chasseur tombe sur deux millions de dollars lors d'une transaction de drogue qui a mal tourné, et est poursuivi par un tueur implacable.",
        "poster_url": "https://image.tmdb.org/t/p/w500/6d5XMGZdbsHy3IO5mFpN6yFuION.jpg",
        "streaming_platforms": ["Netflix", "Paramount+"],
        "avg_rating": 8.1,
        "is_onboarding": 0,
        "fv": [0,1,1,0, 0,0,0,1, 0,0, 0,1,0, 0.81, 1,1,0,0, 0,0],
    },
    {
        "tmdb_id": 210577, "title": "Gone Girl", "year": 2014,
        "director": "David Fincher", "director_id": "fincher",
        "cast": ["Ben Affleck", "Rosamund Pike", "Neil Patrick Harris"],
        "genres": ["Thriller", "Drama", "Crime"],
        "synopsis": "Le jour de son anniversaire de mariage, la femme d'un homme disparaît mystérieusement.",
        "poster_url": "https://image.tmdb.org/t/p/w500/fSRb7vyIP8rQpL0I47P3qUsEKX3.jpg",
        "streaming_platforms": ["Disney+"],
        "avg_rating": 8.1,
        "is_onboarding": 0,
        "fv": [0,1,1,0, 0,0,0,1, 0,0, 0,0,1, 0.81, 1,0,1,0, 0,0],
    },
    {
        "tmdb_id": 1071, "title": "Chinatown", "year": 1974,
        "director": "Roman Polanski", "director_id": "polanski",
        "cast": ["Jack Nicholson", "Faye Dunaway", "John Huston"],
        "genres": ["Thriller", "Crime", "Drama"],
        "synopsis": "Un détective privé se retrouve impliqué dans une conspiration bien plus profonde qu'il ne le pensait.",
        "poster_url": "https://image.tmdb.org/t/p/w500/9chbM7rbh6o0Ok6v6mcT0a3GN9E.jpg",
        "streaming_platforms": ["Mubi"],
        "avg_rating": 8.1,
        "is_onboarding": 0,
        "fv": [0,1,1,0, 0,0,0,1, 0,0, 1,0,0, 0.81, 1,1,0,0, 0,0],
    },
    {
        "tmdb_id": 949, "title": "Heat", "year": 1995,
        "director": "Michael Mann", "director_id": "mann",
        "cast": ["Al Pacino", "Robert De Niro", "Val Kilmer"],
        "genres": ["Crime", "Drama", "Thriller"],
        "synopsis": "Un détective obsessionnel et un maître braqueur se livrent un duel sans merci à Los Angeles.",
        "poster_url": "https://image.tmdb.org/t/p/w500/zMyfPUelumio3tiDKPffaUpsQTD.jpg",
        "streaming_platforms": ["HBO Max"],
        "avg_rating": 8.2,
        "is_onboarding": 0,
        "fv": [1,1,1,0, 0,0,0,1, 0,0, 1,0,0, 0.82, 1,1,0,1, 0,0],
    },
    {
        "tmdb_id": 1422, "title": "The Departed", "year": 2006,
        "director": "Martin Scorsese", "director_id": "scorsese",
        "cast": ["Leonardo DiCaprio", "Matt Damon", "Jack Nicholson"],
        "genres": ["Crime", "Drama", "Thriller"],
        "synopsis": "Un policier infiltre la mafia pendant qu'un gangster s'infiltre dans la police.",
        "poster_url": "https://image.tmdb.org/t/p/w500/nT97ifVT2J1yMQmeq20Qblg61T.jpg",
        "streaming_platforms": ["Netflix", "HBO Max"],
        "avg_rating": 8.5,
        "is_onboarding": 0,
        "fv": [0,1,1,0, 0,0,0,1, 0,0, 0,1,0, 0.85, 1,0,1,1, 0,0],
    },
    {
        "tmdb_id": 273481, "title": "Sicario", "year": 2015,
        "director": "Denis Villeneuve", "director_id": "villeneuve",
        "cast": ["Emily Blunt", "Benicio del Toro", "Josh Brolin"],
        "genres": ["Thriller", "Crime", "Drama"],
        "synopsis": "Une agente du FBI est recrutée pour aider dans une opération secrète contre un cartel de drogue mexicain.",
        "poster_url": "https://image.tmdb.org/t/p/w500/MzNBZZhsEGSR2PTCTuFbEjZoTJ9.jpg",
        "streaming_platforms": ["Netflix", "Prime Video"],
        "avg_rating": 7.6,
        "is_onboarding": 0,
        "fv": [0,1,1,0, 0,0,0,1, 0,0, 0,0,1, 0.76, 1,1,0,0, 0,0],
    },
    # ── Sci-Fi supplémentaires ────────────────────────────────────────────
    {
        "tmdb_id": 78, "title": "Blade Runner", "year": 1982,
        "director": "Ridley Scott", "director_id": "scott_r",
        "cast": ["Harrison Ford", "Rutger Hauer", "Sean Young"],
        "genres": ["SciFi", "Drama", "Thriller"],
        "synopsis": "Un chasseur de réplicants traque des androïdes dans un Los Angeles futuriste et sombre.",
        "poster_url": "https://image.tmdb.org/t/p/w500/63N9uy8nd9j7Ei9EOfNsgPozadE.jpg",
        "streaming_platforms": ["Netflix", "HBO Max"],
        "avg_rating": 8.1,
        "is_onboarding": 0,
        "fv": [0,1,1,0, 0,1,0,0, 0,0, 1,0,0, 0.81, 1,1,0,0, 0,0],
    },
    {
        "tmdb_id": 62, "title": "2001: A Space Odyssey", "year": 1968,
        "director": "Stanley Kubrick", "director_id": "kubrick",
        "cast": ["Keir Dullea", "Gary Lockwood"],
        "genres": ["SciFi", "Drama"],
        "synopsis": "Un voyage spatial vers Jupiter tourne au cauchemar quand l'IA de bord, HAL 9000, devient hostile.",
        "poster_url": "https://image.tmdb.org/t/p/w500/ve72VxNs6yBMd4uUJnfSMmSoYk9.jpg",
        "streaming_platforms": ["Mubi", "HBO Max"],
        "avg_rating": 8.3,
        "is_onboarding": 0,
        "fv": [0,1,0,0, 0,1,0,0, 0,0, 1,0,0, 0.83, 1,1,0,0, 0,0],
    },
    {
        "tmdb_id": 329865, "title": "Arrival", "year": 2016,
        "director": "Denis Villeneuve", "director_id": "villeneuve",
        "cast": ["Amy Adams", "Jeremy Renner", "Forest Whitaker"],
        "genres": ["SciFi", "Drama", "Thriller"],
        "synopsis": "Une linguiste est recrutée par l'armée pour communiquer avec des extraterrestres qui ont atterri sur Terre.",
        "poster_url": "https://image.tmdb.org/t/p/w500/x2FJsf1ElAgr63Y3PNPtJrcmpoe.jpg",
        "streaming_platforms": ["Netflix", "Prime Video"],
        "avg_rating": 7.9,
        "is_onboarding": 0,
        "fv": [0,1,1,0, 0,1,0,0, 0,0, 0,0,1, 0.79, 0,1,1,0, 0,0],
    },
    {
        "tmdb_id": 348, "title": "Alien", "year": 1979,
        "director": "Ridley Scott", "director_id": "scott_r",
        "cast": ["Sigourney Weaver", "Tom Skerritt", "John Hurt"],
        "genres": ["SciFi", "Horror"],
        "synopsis": "L'équipage d'un vaisseau spatial affronte une créature extraterrestre mortelle.",
        "poster_url": "https://image.tmdb.org/t/p/w500/vfrQk5IPloGg1v9Rzbh2Eg3VGyM.jpg",
        "streaming_platforms": ["Disney+", "HBO Max"],
        "avg_rating": 8.5,
        "is_onboarding": 0,
        "fv": [0,0,1,1, 0,1,0,0, 0,0, 1,0,0, 0.85, 1,1,0,0, 0,0],
    },
    {
        "tmdb_id": 152601, "title": "Her", "year": 2013,
        "director": "Spike Jonze", "director_id": "jonze",
        "cast": ["Joaquin Phoenix", "Scarlett Johansson", "Amy Adams"],
        "genres": ["SciFi", "Drama", "Romance"],
        "synopsis": "Un homme solitaire tombe amoureux d'un système d'exploitation doté d'une intelligence artificielle.",
        "poster_url": "https://image.tmdb.org/t/p/w500/lEIaL12hSkqqe83kgADkbUqEnhE.jpg",
        "streaming_platforms": ["Netflix"],
        "avg_rating": 8.0,
        "is_onboarding": 0,
        "fv": [0,1,0,0, 0,1,1,0, 0,0, 0,0,1, 0.80, 0,1,0,0, 0,0],
    },
    {
        "tmdb_id": 438631, "title": "Dune", "year": 2021,
        "director": "Denis Villeneuve", "director_id": "villeneuve",
        "cast": ["Timothée Chalamet", "Rebecca Ferguson", "Oscar Isaac"],
        "genres": ["SciFi", "Action", "Drama"],
        "synopsis": "Un jeune homme hérite d'une planète désertique regorgeant d'une précieuse ressource convoitée par tous.",
        "poster_url": "https://image.tmdb.org/t/p/w500/d5NXSklXo0qyIYkgV94XAgMIckC.jpg",
        "streaming_platforms": ["HBO Max"],
        "avg_rating": 8.0,
        "is_onboarding": 0,
        "fv": [1,1,0,0, 0,1,0,0, 0,0, 0,0,1, 0.80, 1,1,0,1, 0,0],
    },
    # ── Dramas supplémentaires ────────────────────────────────────────────
    {
        "tmdb_id": 389, "title": "12 Angry Men", "year": 1957,
        "director": "Sidney Lumet", "director_id": "lumet",
        "cast": ["Henry Fonda", "Lee J. Cobb", "Martin Balsam"],
        "genres": ["Drama", "Crime"],
        "synopsis": "Douze jurés doivent décider du sort d'un adolescent accusé de meurtre.",
        "poster_url": "https://image.tmdb.org/t/p/w500/ow3wq89wM8qd5X7hWKxiRfsFf9C.jpg",
        "streaming_platforms": ["Mubi", "Prime Video"],
        "avg_rating": 9.0,
        "is_onboarding": 0,
        "fv": [0,1,0,0, 0,0,0,1, 0,0, 1,0,0, 0.90, 0,1,0,1, 0,0],
    },
    {
        "tmdb_id": 14, "title": "American Beauty", "year": 1999,
        "director": "Sam Mendes", "director_id": "mendes",
        "cast": ["Kevin Spacey", "Annette Bening", "Thora Birch"],
        "genres": ["Drama"],
        "synopsis": "Un banlieusard en crise de milieu de vie remet tout en question lors d'une obsession pour la camarade de lycée de sa fille.",
        "poster_url": "https://image.tmdb.org/t/p/w500/wby9315QzAB9e4tLgFKgbMEVNlU.jpg",
        "streaming_platforms": ["Paramount+"],
        "avg_rating": 8.3,
        "is_onboarding": 0,
        "fv": [0,1,0,0, 0,0,0,0, 0,0, 1,0,0, 0.83, 1,0,0,0, 0,0],
    },
    {
        "tmdb_id": 38, "title": "Eternal Sunshine of the Spotless Mind", "year": 2004,
        "director": "Michel Gondry", "director_id": "gondry",
        "cast": ["Jim Carrey", "Kate Winslet", "Tom Wilkinson"],
        "genres": ["SciFi", "Drama", "Romance"],
        "synopsis": "Un homme découvre que son ex-petite amie a fait effacer ses souvenirs de lui, et décide d'en faire autant.",
        "poster_url": "https://image.tmdb.org/t/p/w500/5MwkWH9tYHv3mV9OdYTMR5qreIz.jpg",
        "streaming_platforms": ["Netflix"],
        "avg_rating": 8.3,
        "is_onboarding": 0,
        "fv": [0,1,0,0, 0,1,1,0, 0,0, 0,1,0, 0.83, 0,0,0,0, 0,0],
    },
    {
        "tmdb_id": 106646, "title": "The Wolf of Wall Street", "year": 2013,
        "director": "Martin Scorsese", "director_id": "scorsese",
        "cast": ["Leonardo DiCaprio", "Jonah Hill", "Margot Robbie"],
        "genres": ["Crime", "Drama", "Comedy"],
        "synopsis": "L'ascension et la chute d'un courtier en bourse corrompu dans les années 1980-90.",
        "poster_url": "https://image.tmdb.org/t/p/w500/34m2tygAYBGqA9MXKhRDtzYd4Mg.jpg",
        "streaming_platforms": ["Netflix", "Paramount+"],
        "avg_rating": 8.2,
        "is_onboarding": 0,
        "fv": [0,1,0,0, 1,0,0,1, 0,0, 0,0,1, 0.82, 1,0,0,0, 1,0],
    },
    {
        "tmdb_id": 376867, "title": "Moonlight", "year": 2016,
        "director": "Barry Jenkins", "director_id": "jenkins",
        "cast": ["Trevante Rhodes", "André Holland", "Naomie Harris"],
        "genres": ["Drama"],
        "synopsis": "Un jeune homme noir grandit dans un quartier difficile de Miami, explorant son identité et sa sexualité.",
        "poster_url": "https://image.tmdb.org/t/p/w500/4911T5FbJ9eAlnGqVMDP9OhQmGe.jpg",
        "streaming_platforms": ["Netflix", "Prime Video"],
        "avg_rating": 7.4,
        "is_onboarding": 0,
        "fv": [0,1,0,0, 0,0,0,0, 0,0, 0,0,1, 0.74, 1,1,0,0, 0,0],
    },
    {
        "tmdb_id": 492188, "title": "Marriage Story", "year": 2019,
        "director": "Noah Baumbach", "director_id": "baumbach",
        "cast": ["Adam Driver", "Scarlett Johansson", "Laura Dern"],
        "genres": ["Drama", "Romance"],
        "synopsis": "Un couple new-yorkais traverse un divorce douloureux entre New York et Los Angeles.",
        "poster_url": "https://image.tmdb.org/t/p/w500/e1GJQgFbYFMnbQ76dIUDkfIXNPk.jpg",
        "streaming_platforms": ["Netflix"],
        "avg_rating": 7.9,
        "is_onboarding": 0,
        "fv": [0,1,0,0, 0,0,1,0, 0,0, 0,0,1, 0.79, 1,0,0,0, 0,0],
    },
    {
        "tmdb_id": 497, "title": "The Green Mile", "year": 1999,
        "director": "Frank Darabont", "director_id": "darabont",
        "cast": ["Tom Hanks", "Michael Clarke Duncan", "David Morse"],
        "genres": ["Drama", "Crime"],
        "synopsis": "Les gardiens d'un couloir de la mort sont transformés par leur rencontre avec un condamné aux dons mystérieux.",
        "poster_url": "https://image.tmdb.org/t/p/w500/velWPhVMQeQKcxggNEU8YmU1QcD.jpg",
        "streaming_platforms": ["Netflix"],
        "avg_rating": 8.6,
        "is_onboarding": 0,
        "fv": [0,1,0,0, 0,0,0,1, 0,0, 1,0,0, 0.86, 1,1,0,0, 0,0],
    },
    {
        "tmdb_id": 47933, "title": "Black Swan", "year": 2010,
        "director": "Darren Aronofsky", "director_id": "aronofsky",
        "cast": ["Natalie Portman", "Mila Kunis", "Vincent Cassel"],
        "genres": ["Drama", "Thriller", "Horror"],
        "synopsis": "Une danseuse de ballet perfectionniste bascule dans la folie en cherchant à incarner le cygne noir.",
        "poster_url": "https://image.tmdb.org/t/p/w500/oe2gJNWKOB1VFUkqCRxMl0BXABF.jpg",
        "streaming_platforms": ["Disney+"],
        "avg_rating": 8.0,
        "is_onboarding": 0,
        "fv": [0,1,1,1, 0,0,0,0, 0,0, 0,1,0, 0.80, 1,0,0,0, 0,0],
    },
    # ── Horreur supplémentaire ────────────────────────────────────────────
    {
        "tmdb_id": 419430, "title": "Get Out", "year": 2017,
        "director": "Jordan Peele", "director_id": "peele",
        "cast": ["Daniel Kaluuya", "Allison Williams", "Bradley Whitford"],
        "genres": ["Horror", "Thriller"],
        "synopsis": "Un jeune homme afro-américain rend visite à la famille blanche de sa petite amie et découvre un secret terrifiant.",
        "poster_url": "https://image.tmdb.org/t/p/w500/tFXcEccSQMf3lfhfXKSU9iRBpa3.jpg",
        "streaming_platforms": ["Peacock", "Prime Video"],
        "avg_rating": 7.7,
        "is_onboarding": 0,
        "fv": [0,0,1,1, 0,0,0,0, 0,0, 0,0,1, 0.77, 1,0,1,0, 0,0],
    },
    {
        "tmdb_id": 9552, "title": "The Exorcist", "year": 1973,
        "director": "William Friedkin", "director_id": "friedkin",
        "cast": ["Ellen Burstyn", "Max von Sydow", "Linda Blair"],
        "genres": ["Horror", "Drama"],
        "synopsis": "Une jeune fille est possédée par une entité démoniaque et sa mère fait appel à deux prêtres.",
        "poster_url": "https://image.tmdb.org/t/p/w500/4eJFXpBGCZk0sVPQ3CPhOJKMVFM.jpg",
        "streaming_platforms": ["HBO Max"],
        "avg_rating": 8.1,
        "is_onboarding": 0,
        "fv": [0,1,0,1, 0,0,0,0, 0,0, 1,0,0, 0.81, 1,1,0,0, 0,0],
    },
    {
        "tmdb_id": 530385, "title": "Midsommar", "year": 2019,
        "director": "Ari Aster", "director_id": "aster",
        "cast": ["Florence Pugh", "Jack Reynor", "William Jackson Harper"],
        "genres": ["Horror", "Drama"],
        "synopsis": "Un groupe d'amis américains assiste à un festival estival en Suède qui révèle des rites de plus en plus inquiétants.",
        "poster_url": "https://image.tmdb.org/t/p/w500/7LEI8ulZzO5gy9Ww2NVCrKmHeDZ.jpg",
        "streaming_platforms": ["Prime Video", "Mubi"],
        "avg_rating": 7.1,
        "is_onboarding": 0,
        "fv": [0,1,0,1, 0,0,0,0, 0,0, 0,0,1, 0.71, 1,1,0,0, 0,0],
    },
    {
        "tmdb_id": 574, "title": "Rosemary's Baby", "year": 1968,
        "director": "Roman Polanski", "director_id": "polanski",
        "cast": ["Mia Farrow", "John Cassavetes", "Ruth Gordon"],
        "genres": ["Horror", "Drama"],
        "synopsis": "Une jeune femme enceinte soupçonne ses voisins de comploter autour de son enfant à naître.",
        "poster_url": "https://image.tmdb.org/t/p/w500/isBJHZJQZPFkMJMTMwz1z5Bp3F7.jpg",
        "streaming_platforms": ["Paramount+"],
        "avg_rating": 8.0,
        "is_onboarding": 0,
        "fv": [0,1,0,1, 0,0,0,0, 0,0, 1,0,0, 0.80, 1,1,0,0, 0,0],
    },
    {
        "tmdb_id": 259695, "title": "The Witch", "year": 2015,
        "director": "Robert Eggers", "director_id": "eggers",
        "cast": ["Anya Taylor-Joy", "Ralph Ineson", "Kate Dickie"],
        "genres": ["Horror", "Drama"],
        "synopsis": "Une famille puritaine du XVIIe siècle est terrorisée par une présence maléfique dans les bois voisins.",
        "poster_url": "https://image.tmdb.org/t/p/w500/bFHFITuxdJr4mTmMJDHN1M7HsAz.jpg",
        "streaming_platforms": ["Prime Video"],
        "avg_rating": 6.9,
        "is_onboarding": 0,
        "fv": [0,1,0,1, 0,0,0,0, 0,0, 0,0,1, 0.69, 1,1,0,0, 0,0],
    },
    # ── Comédies supplémentaires ──────────────────────────────────────────
    {
        "tmdb_id": 115, "title": "The Big Lebowski", "year": 1998,
        "director": "Joel Coen", "director_id": "coen",
        "cast": ["Jeff Bridges", "John Goodman", "Julianne Moore"],
        "genres": ["Comedy", "Crime"],
        "synopsis": "Un fainéant amateur de bowling est confondu avec un millionnaire et se retrouve mêlé à une affaire d'enlèvement.",
        "poster_url": "https://image.tmdb.org/t/p/w500/tFpA1KRENnPF2TS1KxYAuSPJN5R.jpg",
        "streaming_platforms": ["Netflix"],
        "avg_rating": 8.1,
        "is_onboarding": 0,
        "fv": [0,0,0,0, 1,0,0,1, 0,0, 1,0,0, 0.81, 0,0,0,1, 0,0],
    },
    {
        "tmdb_id": 137, "title": "Groundhog Day", "year": 1993,
        "director": "Harold Ramis", "director_id": "ramis",
        "cast": ["Bill Murray", "Andie MacDowell", "Chris Elliott"],
        "genres": ["Comedy", "Drama", "Romance"],
        "synopsis": "Un journaliste météo revit indéfiniment le même jour jusqu'à ce qu'il change de comportement.",
        "poster_url": "https://image.tmdb.org/t/p/w500/gUfFGaVRfJCGNXWNSuJx9UL9Laa.jpg",
        "streaming_platforms": ["Netflix"],
        "avg_rating": 8.0,
        "is_onboarding": 0,
        "fv": [0,1,0,0, 1,0,1,0, 0,0, 1,0,0, 0.80, 0,0,1,0, 0,0],
    },
    {
        "tmdb_id": 10529, "title": "In Bruges", "year": 2008,
        "director": "Martin McDonagh", "director_id": "mcdonagh",
        "cast": ["Colin Farrell", "Brendan Gleeson", "Ralph Fiennes"],
        "genres": ["Comedy", "Crime", "Drama"],
        "synopsis": "Deux tueurs à gages se retrouvent cachés dans la ville de Bruges après une mission qui a mal tourné.",
        "poster_url": "https://image.tmdb.org/t/p/w500/d0KaJMxGF90LOxJFQlVnfzSVvOb.jpg",
        "streaming_platforms": ["Prime Video"],
        "avg_rating": 7.9,
        "is_onboarding": 0,
        "fv": [0,1,0,0, 1,0,0,1, 0,0, 0,1,0, 0.79, 1,0,0,0, 0,0],
    },
    {
        "tmdb_id": 889, "title": "Some Like It Hot", "year": 1959,
        "director": "Billy Wilder", "director_id": "wilder",
        "cast": ["Marilyn Monroe", "Tony Curtis", "Jack Lemmon"],
        "genres": ["Comedy", "Romance"],
        "synopsis": "Deux musiciens se déguisent en femmes pour fuir la mafia et rejoignent un orchestre féminin.",
        "poster_url": "https://image.tmdb.org/t/p/w500/cHEr3yB1bfIHGhGJZpBdNXCIAOw.jpg",
        "streaming_platforms": ["Mubi"],
        "avg_rating": 8.2,
        "is_onboarding": 0,
        "fv": [0,0,0,0, 1,0,1,0, 0,0, 1,0,0, 0.82, 0,0,0,1, 0,0],
    },
    # ── Animation supplémentaire ──────────────────────────────────────────
    {
        "tmdb_id": 14160, "title": "Up", "year": 2009,
        "director": "Pete Docter", "director_id": "docter",
        "cast": ["Edward Asner", "Jordan Nagai", "John Ratzenberger"],
        "genres": ["Animation", "Comedy", "Drama"],
        "synopsis": "Un vieillard réalise le rêve de sa vie en attachant des milliers de ballons à sa maison pour partir en Amérique du Sud.",
        "poster_url": "https://image.tmdb.org/t/p/w500/9k4sgLkFRfE4QRFRv9ENMiPWvXm.jpg",
        "streaming_platforms": ["Disney+"],
        "avg_rating": 8.3,
        "is_onboarding": 0,
        "fv": [0,1,0,0, 1,0,0,0, 1,0, 0,1,0, 0.83, 1,0,0,0, 0,0],
    },
    {
        "tmdb_id": 10681, "title": "WALL-E", "year": 2008,
        "director": "Andrew Stanton", "director_id": "stanton",
        "cast": ["Ben Burtt", "Elissa Knight"],
        "genres": ["Animation", "SciFi", "Romance"],
        "synopsis": "Un petit robot éboueur solitaire sur une Terre abandonnée tombe amoureux d'un robot explorateur.",
        "poster_url": "https://image.tmdb.org/t/p/w500/hbhFnRzzg6ZDmm8YAmxBnwESFbp.jpg",
        "streaming_platforms": ["Disney+"],
        "avg_rating": 8.4,
        "is_onboarding": 0,
        "fv": [0,1,0,0, 0,1,1,0, 1,0, 0,1,0, 0.84, 0,0,0,0, 0,0],
    },
    {
        "tmdb_id": 128, "title": "Princess Mononoke", "year": 1997,
        "director": "Hayao Miyazaki", "director_id": "miyazaki",
        "cast": ["Yoji Matsuda", "Yuriko Ishida", "Yuko Tanaka"],
        "genres": ["Animation", "Action", "Fantasy"],
        "synopsis": "Un jeune prince se retrouve pris entre une forêt hantée et une ville minière qui empiète dessus.",
        "poster_url": "https://image.tmdb.org/t/p/w500/jHffK1pWe5gBtkeFzqHqHaRSgUZ.jpg",
        "streaming_platforms": ["Netflix"],
        "avg_rating": 8.4,
        "is_onboarding": 0,
        "fv": [1,1,0,0, 0,0,0,0, 1,0, 1,0,0, 0.84, 1,0,0,0, 0,1],
    },
    {
        "tmdb_id": 2062, "title": "Ratatouille", "year": 2007,
        "director": "Brad Bird", "director_id": "bird",
        "cast": ["Patton Oswalt", "Ian Holm", "Lou Romano"],
        "genres": ["Animation", "Comedy", "Drama"],
        "synopsis": "Un rat passionné de cuisine aspire à devenir chef dans un grand restaurant parisien.",
        "poster_url": "https://image.tmdb.org/t/p/w500/npHNjldbeTHdKKv31wAfVJQCool.jpg",
        "streaming_platforms": ["Disney+"],
        "avg_rating": 8.1,
        "is_onboarding": 0,
        "fv": [0,1,0,0, 1,0,0,0, 1,0, 0,1,0, 0.81, 0,0,0,0, 0,1],
    },
    {
        "tmdb_id": 8587, "title": "The Lion King", "year": 1994,
        "director": "Roger Allers", "director_id": "allers",
        "cast": ["Matthew Broderick", "Jeremy Irons", "James Earl Jones"],
        "genres": ["Animation", "Drama"],
        "synopsis": "Un jeune lion doit revendiquer son héritage royal après le meurtre de son père.",
        "poster_url": "https://image.tmdb.org/t/p/w500/sKCr78MXSuS2IiKd2W1TOfvOVvI.jpg",
        "streaming_platforms": ["Disney+"],
        "avg_rating": 8.5,
        "is_onboarding": 0,
        "fv": [0,1,0,0, 0,0,0,0, 1,0, 1,0,0, 0.85, 1,0,0,0, 0,0],
    },
    # ── Action / Guerre supplémentaires ───────────────────────────────────
    {
        "tmdb_id": 98, "title": "Gladiator", "year": 2000,
        "director": "Ridley Scott", "director_id": "scott_r",
        "cast": ["Russell Crowe", "Joaquin Phoenix", "Connie Nielsen"],
        "genres": ["Action", "Drama"],
        "synopsis": "Un général romain trahi est réduit en esclavage et cherche à se venger de l'usurpateur du trône.",
        "poster_url": "https://image.tmdb.org/t/p/w500/ty8TGRuvJLPUmAR1H1nRIsgwvim.jpg",
        "streaming_platforms": ["Netflix", "Paramount+"],
        "avg_rating": 8.5,
        "is_onboarding": 0,
        "fv": [1,1,0,0, 0,0,0,0, 0,0, 0,1,0, 0.85, 1,0,0,0, 0,0],
    },
    {
        "tmdb_id": 1571, "title": "Die Hard", "year": 1988,
        "director": "John McTiernan", "director_id": "mctiernan",
        "cast": ["Bruce Willis", "Alan Rickman", "Bonnie Bedelia"],
        "genres": ["Action", "Thriller"],
        "synopsis": "Un policier new-yorkais doit affronter seul des terroristes qui ont pris en otage un immeuble de bureaux.",
        "poster_url": "https://image.tmdb.org/t/p/w500/yFihWxQcmqcaBR31QM6Y8gT6aYV.jpg",
        "streaming_platforms": ["Disney+"],
        "avg_rating": 8.2,
        "is_onboarding": 0,
        "fv": [1,0,1,0, 0,0,0,0, 0,0, 1,0,0, 0.82, 0,0,0,0, 0,0],
    },
    {
        "tmdb_id": 857, "title": "Saving Private Ryan", "year": 1998,
        "director": "Steven Spielberg", "director_id": "spielberg",
        "cast": ["Tom Hanks", "Matt Damon", "Tom Sizemore"],
        "genres": ["Action", "Drama"],
        "synopsis": "Après le débarquement de Normandie, un groupe de soldats est envoyé pour retrouver et ramener un soldat.",
        "poster_url": "https://image.tmdb.org/t/p/w500/uqx37cS8cpHg8U35f9U5IBlrCV3.jpg",
        "streaming_platforms": ["Paramount+"],
        "avg_rating": 8.6,
        "is_onboarding": 0,
        "fv": [1,1,0,0, 0,0,0,0, 0,0, 1,0,0, 0.86, 1,0,0,1, 0,0],
    },
    {
        "tmdb_id": 245891, "title": "John Wick", "year": 2014,
        "director": "Chad Stahelski", "director_id": "stahelski",
        "cast": ["Keanu Reeves", "Michael Nyqvist", "Alfie Allen"],
        "genres": ["Action", "Thriller", "Crime"],
        "synopsis": "Un ancien tueur à gages sort de sa retraite pour se venger de ceux qui ont tué son chien.",
        "poster_url": "https://image.tmdb.org/t/p/w500/fZPSd91yGE9fCcCe6OoQr6E3Bev.jpg",
        "streaming_platforms": ["Netflix", "Prime Video"],
        "avg_rating": 7.4,
        "is_onboarding": 0,
        "fv": [1,0,1,0, 0,0,0,1, 0,0, 0,0,1, 0.74, 1,0,0,0, 0,0],
    },
    {
        "tmdb_id": 28, "title": "Apocalypse Now", "year": 1979,
        "director": "Francis Ford Coppola", "director_id": "coppola",
        "cast": ["Martin Sheen", "Marlon Brando", "Robert Duvall"],
        "genres": ["Action", "Drama"],
        "synopsis": "Un capitaine est envoyé au cœur du Vietnam pour éliminer un colonel devenu fou.",
        "poster_url": "https://image.tmdb.org/t/p/w500/gQB8Y5RCMkv2zwzFHbUJX3kAhvA.jpg",
        "streaming_platforms": ["Mubi"],
        "avg_rating": 8.5,
        "is_onboarding": 0,
        "fv": [1,1,0,0, 0,0,0,0, 0,0, 1,0,0, 0.85, 1,1,0,1, 0,0],
    },
    # ── Westerns ──────────────────────────────────────────────────────────
    {
        "tmdb_id": 1253, "title": "The Good, the Bad and the Ugly", "year": 1966,
        "director": "Sergio Leone", "director_id": "leone",
        "cast": ["Clint Eastwood", "Eli Wallach", "Lee Van Cleef"],
        "genres": ["Action", "Drama"],
        "synopsis": "Trois hommes aux intérêts opposés cherchent un trésor enfoui pendant la guerre de Sécession.",
        "poster_url": "https://image.tmdb.org/t/p/w500/bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg",
        "streaming_platforms": ["Mubi"],
        "avg_rating": 8.8,
        "is_onboarding": 0,
        "fv": [1,1,0,0, 0,0,0,0, 0,0, 1,0,0, 0.88, 1,1,0,0, 0,0],
    },
    {
        "tmdb_id": 2769, "title": "Unforgiven", "year": 1992,
        "director": "Clint Eastwood", "director_id": "eastwood",
        "cast": ["Clint Eastwood", "Gene Hackman", "Morgan Freeman"],
        "genres": ["Drama", "Action"],
        "synopsis": "Un ancien tueur à gages reprend les armes pour une dernière mission dans le Far West.",
        "poster_url": "https://image.tmdb.org/t/p/w500/ggoBBxEpM8hMPXzT2CQJLS6bZCm.jpg",
        "streaming_platforms": ["Netflix"],
        "avg_rating": 8.2,
        "is_onboarding": 0,
        "fv": [1,1,0,0, 0,0,0,0, 0,0, 1,0,0, 0.82, 1,1,0,0, 0,0],
    },
    # ── Films étrangers / Art House ───────────────────────────────────────
    {
        "tmdb_id": 1408, "title": "Pan's Labyrinth", "year": 2006,
        "director": "Guillermo del Toro", "director_id": "deltoro",
        "cast": ["Ivana Baquero", "Sergi López", "Doug Jones"],
        "genres": ["Drama", "Fantasy", "Horror"],
        "synopsis": "Dans l'Espagne franquiste, une petite fille s'évade dans un monde fantastique souterrain.",
        "poster_url": "https://image.tmdb.org/t/p/w500/htYtYiT0xEFY6UHuH5PJRQjhRNs.jpg",
        "streaming_platforms": ["HBO Max"],
        "avg_rating": 8.2,
        "is_onboarding": 0,
        "fv": [0,1,0,1, 0,0,0,0, 0,0, 0,1,0, 0.82, 1,0,0,0, 0,1],
    },
    {
        "tmdb_id": 11216, "title": "Cinema Paradiso", "year": 1988,
        "director": "Giuseppe Tornatore", "director_id": "tornatore",
        "cast": ["Philippe Noiret", "Jacques Perrin", "Salvatore Cascio"],
        "genres": ["Drama", "Romance"],
        "synopsis": "Un réalisateur se souvient de son enfance en Sicile et de sa passion pour le cinéma.",
        "poster_url": "https://image.tmdb.org/t/p/w500/9HjJ7bMt8yBMLcSaKKxRjrSmEuN.jpg",
        "streaming_platforms": ["Mubi"],
        "avg_rating": 8.5,
        "is_onboarding": 0,
        "fv": [0,1,0,0, 0,0,1,0, 0,0, 1,0,0, 0.85, 0,1,0,0, 0,1],
    },
    {
        "tmdb_id": 75780, "title": "Intouchables", "year": 2011,
        "director": "Olivier Nakache", "director_id": "nakache",
        "cast": ["François Cluzet", "Omar Sy", "Anne Le Ny"],
        "genres": ["Drama", "Comedy"],
        "synopsis": "L'amitié improbable entre un aristocrate tétraplégique et un jeune homme des banlieues.",
        "poster_url": "https://image.tmdb.org/t/p/w500/1e2ckgEMOmBfDFSFxXpBdEFqPBa.jpg",
        "streaming_platforms": ["Netflix"],
        "avg_rating": 8.5,
        "is_onboarding": 0,
        "fv": [0,1,0,0, 1,0,0,0, 0,0, 0,1,0, 0.85, 0,0,0,0, 1,1],
    },
    {
        "tmdb_id": 843, "title": "In the Mood for Love", "year": 2000,
        "director": "Wong Kar-wai", "director_id": "wongkarwai",
        "cast": ["Tony Leung Chiu-wai", "Maggie Cheung"],
        "genres": ["Drama", "Romance"],
        "synopsis": "Deux voisins découvrent que leurs conjoints respectifs ont une liaison, et nouent un lien ambigu.",
        "poster_url": "https://image.tmdb.org/t/p/w500/8d5XYPxSyKLqEGMW0hL7sSmtqBx.jpg",
        "streaming_platforms": ["Mubi"],
        "avg_rating": 8.1,
        "is_onboarding": 0,
        "fv": [0,1,0,0, 0,0,1,0, 0,0, 0,1,0, 0.81, 1,1,0,0, 0,1],
    },
    {
        "tmdb_id": 387, "title": "Das Boot", "year": 1981,
        "director": "Wolfgang Petersen", "director_id": "petersen",
        "cast": ["Jürgen Prochnow", "Herbert Grönemeyer", "Klaus Wennemann"],
        "genres": ["Drama", "Action"],
        "synopsis": "L'équipage d'un sous-marin allemand vit dans l'enfer de la Seconde Guerre mondiale en Atlantique.",
        "poster_url": "https://image.tmdb.org/t/p/w500/8HtELqRXQFVlAUhHGIMZNEDXn0A.jpg",
        "streaming_platforms": ["Mubi"],
        "avg_rating": 8.4,
        "is_onboarding": 0,
        "fv": [1,1,0,0, 0,0,0,0, 0,0, 1,0,0, 0.84, 1,1,0,1, 0,1],
    },
    {
        "tmdb_id": 72105, "title": "A Separation", "year": 2011,
        "director": "Asghar Farhadi", "director_id": "farhadi",
        "cast": ["Leila Hatami", "Peyman Moaadi", "Shahab Hosseini"],
        "genres": ["Drama"],
        "synopsis": "Un couple iranien se dispute la garde de leur fille lors d'une procédure de séparation.",
        "poster_url": "https://image.tmdb.org/t/p/w500/fiCGiXIBfHKe3V7PgQjqgvsuyHW.jpg",
        "streaming_platforms": ["Mubi"],
        "avg_rating": 8.3,
        "is_onboarding": 0,
        "fv": [0,1,0,0, 0,0,0,0, 0,0, 0,1,0, 0.83, 1,0,0,0, 0,1],
    },
    {
        "tmdb_id": 670, "title": "Oldboy", "year": 2003,
        "director": "Park Chan-wook", "director_id": "parkchanwook",
        "cast": ["Choi Min-sik", "Yoo Ji-tae", "Kang Hye-jung"],
        "genres": ["Thriller", "Drama", "Crime"],
        "synopsis": "Un homme libéré après 15 ans d'emprisonnement mystérieux cherche à comprendre pourquoi il a été enfermé.",
        "poster_url": "https://image.tmdb.org/t/p/w500/cB3hTHlENNHk9O9vLoYcPOlCBgS.jpg",
        "streaming_platforms": ["Mubi"],
        "avg_rating": 8.4,
        "is_onboarding": 0,
        "fv": [0,1,1,0, 0,0,0,1, 0,0, 0,1,0, 0.84, 1,0,1,0, 0,1],
    },
]
# fmt: on

VECTOR_DIM = 20


def normalize(v: list) -> list:
    norm = math.sqrt(sum(x * x for x in v))
    if norm == 0:
        return v
    return [x / norm for x in v]


async def seed():
    await create_tables()
    async with aiosqlite.connect(database.DB_PATH) as db:
        # Check if already seeded
        cursor = await db.execute("SELECT COUNT(*) FROM movies")
        count = (await cursor.fetchone())[0]
        if count >= len(MOVIES):
            print(f"Database already seeded with {count} movies. Skipping.")
            return
        if count > 0:
            print(f"Catalog updated: adding {len(MOVIES) - count} new movies (had {count}, need {len(MOVIES)}).")

        # Fetch existing titles to avoid duplicates
        cursor = await db.execute("SELECT title FROM movies")
        existing_titles = {row[0] for row in await cursor.fetchall()}

        inserted = 0
        for m in MOVIES:
            if m["title"] in existing_titles:
                continue
            fv = normalize(m["fv"])
            await db.execute(
                """INSERT INTO movies
                   (tmdb_id, title, year, director, director_id, cast, genres,
                    synopsis, poster_url, streaming_platforms, avg_rating,
                    feature_vector, is_onboarding)
                   VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)""",
                (
                    m["tmdb_id"],
                    m["title"],
                    m["year"],
                    m["director"],
                    m["director_id"],
                    json.dumps(m["cast"]),
                    json.dumps(m["genres"]),
                    m["synopsis"],
                    m["poster_url"],
                    json.dumps(m["streaming_platforms"]),
                    m["avg_rating"],
                    json.dumps(fv),
                    m["is_onboarding"],
                ),
            )
            inserted += 1
        await db.commit()
        print(f"Seeded {inserted} movies into the database (total: {count + inserted}).")


async def seed_from_tmdb() -> int:
    """Fetch movies from TMDB and insert them (skip existing tmdb_ids).

    Only runs when TMDB_API_KEY is set and the catalog has fewer than 200 movies.
    Returns the number of newly inserted movies.
    """
    api_key = os.environ.get("TMDB_API_KEY")
    if not api_key:
        return 0

    async with aiosqlite.connect(database.DB_PATH) as db:
        cursor = await db.execute("SELECT COUNT(*) FROM movies")
        count = (await cursor.fetchone())[0]
        if count >= 200:
            print(f"TMDB seed skipped — catalog already has {count} movies.")
            return 0

    from tmdb import fetch_movies  # local import avoids circular deps at module load

    print(f"Fetching movies from TMDB (catalog has {count} films)…")
    movies = await fetch_movies(api_key)
    print(f"TMDB returned {len(movies)} candidates.")

    inserted = 0
    async with aiosqlite.connect(database.DB_PATH) as db:
        cursor = await db.execute("SELECT tmdb_id FROM movies WHERE tmdb_id IS NOT NULL")
        existing_tmdb_ids = {row[0] for row in await cursor.fetchall()}

        for m in movies:
            if m["tmdb_id"] in existing_tmdb_ids:
                continue
            await db.execute(
                """INSERT INTO movies
                   (tmdb_id, title, year, director, director_id, cast, genres,
                    synopsis, poster_url, streaming_platforms, avg_rating,
                    feature_vector, is_onboarding)
                   VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)""",
                (
                    m["tmdb_id"],
                    m["title"],
                    m["year"],
                    m["director"],
                    m["director_id"],
                    json.dumps(m["cast"]),
                    json.dumps(m["genres"]),
                    m["synopsis"],
                    m["poster_url"],
                    json.dumps(m["streaming_platforms"]),
                    m["avg_rating"],
                    json.dumps(m["feature_vector"]),
                    m["is_onboarding"],
                ),
            )
            existing_tmdb_ids.add(m["tmdb_id"])
            inserted += 1

        await db.commit()

    print(f"TMDB seed complete: {inserted} new movies added.")
    return inserted


if __name__ == "__main__":
    asyncio.run(seed())
