"""
Seed 50+ iconic films into the database.

Feature vector dimensions (20 total):
  0: Action       1: Drama        2: Thriller     3: Horror
  4: Comedy       5: SciFi        6: Romance      7: Crime
  8: Animation    9: Documentary
  10: pre-2000    11: 2000s       12: 2010s+
  13: avg_rating normalized (0-1, rating/10)
  14: dark        15: slow-burn   16: plot-twist  17: ensemble-cast
  18: biographical  19: foreign-language
"""

import asyncio
import json
import math
from database import create_tables
import aiosqlite
from pathlib import Path

DB_PATH = Path(__file__).parent / "moviefinder.db"

# fmt: off
MOVIES = [
    # ── Thrillers / Crime ──────────────────────────────────────────────────
    {
        "tmdb_id": 807, "title": "Se7en", "year": 1995,
        "director": "David Fincher", "director_id": "fincher",
        "cast": ["Brad Pitt", "Morgan Freeman", "Kevin Spacey"],
        "genres": ["Thriller", "Crime", "Drama"],
        "synopsis": "Deux détectives traquent un tueur en série s'inspirant des sept péchés capitaux.",
        "poster_url": "https://image.tmdb.org/t/p/w500/6yoghtyTpznpBik8EngEmJskVUO.jpg",
        "streaming_platforms": ["Netflix"],
        "avg_rating": 8.6,
        "is_onboarding": 1,
        # Action, Drama, Thriller, Horror, Comedy, SciFi, Romance, Crime, Anim, Doc
        # pre2k, 2000s, 2010s+, rating, dark, slow-burn, plot-twist, ensemble, bio, foreign
        "fv": [0,1,1,0, 0,0,0,1, 0,0, 1,0,0, 0.86, 1,1,1,0, 0,0],
    },
    {
        "tmdb_id": 680, "title": "Pulp Fiction", "year": 1994,
        "director": "Quentin Tarantino", "director_id": "tarantino",
        "cast": ["John Travolta", "Uma Thurman", "Samuel L. Jackson"],
        "genres": ["Crime", "Drama"],
        "synopsis": "Des histoires entrelacées de criminels à Los Angeles.",
        "poster_url": "https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
        "streaming_platforms": ["Prime Video"],
        "avg_rating": 8.9,
        "is_onboarding": 1,
        "fv": [0,1,0,0, 0,0,0,1, 0,0, 1,0,0, 0.89, 1,0,1,1, 0,0],
    },
    {
        "tmdb_id": 769, "title": "GoodFellas", "year": 1990,
        "director": "Martin Scorsese", "director_id": "scorsese",
        "cast": ["Ray Liotta", "Robert De Niro", "Joe Pesci"],
        "genres": ["Crime", "Drama"],
        "synopsis": "L'ascension et la chute d'un gangster dans la mafia new-yorkaise.",
        "poster_url": "https://image.tmdb.org/t/p/w500/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg",
        "streaming_platforms": ["Netflix"],
        "avg_rating": 8.7,
        "is_onboarding": 1,
        "fv": [0,1,0,0, 0,0,0,1, 0,0, 1,0,0, 0.87, 1,0,0,1, 0,0],
    },
    {
        "tmdb_id": 238, "title": "The Godfather", "year": 1972,
        "director": "Francis Ford Coppola", "director_id": "coppola",
        "cast": ["Marlon Brando", "Al Pacino", "James Caan"],
        "genres": ["Crime", "Drama"],
        "synopsis": "Le patriarche d'une famille de la mafia transfère le contrôle de son empire clandestin à son fils réticent.",
        "poster_url": "https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsLeFJfQ8CK2C.jpg",
        "streaming_platforms": ["Prime Video", "Paramount+"],
        "avg_rating": 9.2,
        "is_onboarding": 1,
        "fv": [0,1,0,0, 0,0,0,1, 0,0, 1,0,0, 0.92, 1,1,0,1, 0,0],
    },
    {
        "tmdb_id": 155, "title": "The Dark Knight", "year": 2008,
        "director": "Christopher Nolan", "director_id": "nolan",
        "cast": ["Christian Bale", "Heath Ledger", "Aaron Eckhart"],
        "genres": ["Action", "Drama", "Crime"],
        "synopsis": "Batman affronte le Joker, un criminel anarchiste qui sème le chaos à Gotham City.",
        "poster_url": "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
        "streaming_platforms": ["Netflix", "HBO Max"],
        "avg_rating": 9.0,
        "is_onboarding": 1,
        "fv": [1,1,0,0, 0,0,0,1, 0,0, 0,1,0, 0.90, 1,0,1,0, 0,0],
    },
    {
        "tmdb_id": 278, "title": "The Shawshank Redemption", "year": 1994,
        "director": "Frank Darabont", "director_id": "darabont",
        "cast": ["Tim Robbins", "Morgan Freeman"],
        "genres": ["Drama"],
        "synopsis": "Un banquier innocemment condamné noue une amitié profonde en prison.",
        "poster_url": "https://image.tmdb.org/t/p/w500/lyQBXzOQSuE59IsHyhrp0qIiPAz.jpg",
        "streaming_platforms": ["Netflix"],
        "avg_rating": 9.3,
        "is_onboarding": 0,
        "fv": [0,1,0,0, 0,0,0,0, 0,0, 1,0,0, 0.93, 1,1,0,0, 0,0],
    },
    {
        "tmdb_id": 550, "title": "Fight Club", "year": 1999,
        "director": "David Fincher", "director_id": "fincher",
        "cast": ["Brad Pitt", "Edward Norton", "Helena Bonham Carter"],
        "genres": ["Drama", "Thriller"],
        "synopsis": "Un cadre insatisfait fonde avec un vendeur de savon mystérieux un club de combat clandestin.",
        "poster_url": "https://image.tmdb.org/t/p/w500/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg",
        "streaming_platforms": ["Disney+"],
        "avg_rating": 8.8,
        "is_onboarding": 1,
        "fv": [0,1,1,0, 0,0,0,0, 0,0, 1,0,0, 0.88, 1,0,1,0, 0,0],
    },
    {
        "tmdb_id": 13, "title": "Forrest Gump", "year": 1994,
        "director": "Robert Zemeckis", "director_id": "zemeckis",
        "cast": ["Tom Hanks", "Robin Wright", "Gary Sinise"],
        "genres": ["Drama", "Romance"],
        "synopsis": "Les aventures d'un homme au grand cœur à travers l'histoire américaine moderne.",
        "poster_url": "https://image.tmdb.org/t/p/w500/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg",
        "streaming_platforms": ["Netflix", "Paramount+"],
        "avg_rating": 8.8,
        "is_onboarding": 0,
        "fv": [0,1,0,0, 0,0,1,0, 0,0, 1,0,0, 0.88, 0,0,0,0, 0,0],
    },
    # ── Sci-Fi ────────────────────────────────────────────────────────────
    {
        "tmdb_id": 157336, "title": "Interstellar", "year": 2014,
        "director": "Christopher Nolan", "director_id": "nolan",
        "cast": ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain"],
        "genres": ["SciFi", "Drama"],
        "synopsis": "Un groupe d'explorateurs voyage à travers un trou de ver pour assurer la survie de l'humanité.",
        "poster_url": "https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
        "streaming_platforms": ["Netflix", "Prime Video"],
        "avg_rating": 8.6,
        "is_onboarding": 1,
        "fv": [0,1,0,0, 0,1,0,0, 0,0, 0,0,1, 0.86, 0,1,1,0, 0,0],
    },
    {
        "tmdb_id": 27205, "title": "Inception", "year": 2010,
        "director": "Christopher Nolan", "director_id": "nolan",
        "cast": ["Leonardo DiCaprio", "Joseph Gordon-Levitt", "Elliot Page"],
        "genres": ["SciFi", "Action", "Thriller"],
        "synopsis": "Un voleur qui s'infiltre dans les rêves se voit offrir la chance d'effacer son passé.",
        "poster_url": "https://image.tmdb.org/t/p/w500/edv5CZvWj09upOsy2Y6IwDhK8bt.jpg",
        "streaming_platforms": ["Netflix", "HBO Max"],
        "avg_rating": 8.8,
        "is_onboarding": 0,
        "fv": [1,0,1,0, 0,1,0,0, 0,0, 0,1,0, 0.88, 0,0,1,1, 0,0],
    },
    {
        "tmdb_id": 603, "title": "The Matrix", "year": 1999,
        "director": "Lana Wachowski", "director_id": "wachowski",
        "cast": ["Keanu Reeves", "Laurence Fishburne", "Carrie-Anne Moss"],
        "genres": ["SciFi", "Action"],
        "synopsis": "Un hacker découvre que la réalité telle qu'il la connaît est une simulation.",
        "poster_url": "https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg",
        "streaming_platforms": ["Netflix", "HBO Max"],
        "avg_rating": 8.7,
        "is_onboarding": 0,
        "fv": [1,0,0,0, 0,1,0,0, 0,0, 1,0,0, 0.87, 1,0,1,0, 0,0],
    },
    {
        "tmdb_id": 862, "title": "Toy Story", "year": 1995,
        "director": "John Lasseter", "director_id": "lasseter",
        "cast": ["Tom Hanks", "Tim Allen"],
        "genres": ["Animation", "Comedy"],
        "synopsis": "Les jouets d'un enfant prennent vie et vivent leurs propres aventures.",
        "poster_url": "https://image.tmdb.org/t/p/w500/uXDfjJbdP4ijW5hWSBrPivLqxyd.jpg",
        "streaming_platforms": ["Disney+"],
        "avg_rating": 8.3,
        "is_onboarding": 0,
        "fv": [0,0,0,0, 1,0,0,0, 1,0, 1,0,0, 0.83, 0,0,0,0, 0,0],
    },
    {
        "tmdb_id": 424, "title": "Schindler's List", "year": 1993,
        "director": "Steven Spielberg", "director_id": "spielberg",
        "cast": ["Liam Neeson", "Ben Kingsley", "Ralph Fiennes"],
        "genres": ["Drama", "History"],
        "synopsis": "Un industriel allemand sauve plus d'un millier de Juifs polonais de l'Holocauste.",
        "poster_url": "https://image.tmdb.org/t/p/w500/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg",
        "streaming_platforms": ["Prime Video"],
        "avg_rating": 9.0,
        "is_onboarding": 0,
        "fv": [0,1,0,0, 0,0,0,0, 0,0, 1,0,0, 0.90, 1,1,0,0, 1,0],
    },
    # ── Horror ────────────────────────────────────────────────────────────
    {
        "tmdb_id": 694, "title": "The Shining", "year": 1980,
        "director": "Stanley Kubrick", "director_id": "kubrick",
        "cast": ["Jack Nicholson", "Shelley Duvall"],
        "genres": ["Horror", "Drama"],
        "synopsis": "Un écrivain s'installe comme gardien d'un hôtel isolé avec sa famille, et sombre dans la folie.",
        "poster_url": "https://image.tmdb.org/t/p/w500/nRj5511mZdTl4saWEPoj9QroTIu.jpg",
        "streaming_platforms": ["HBO Max"],
        "avg_rating": 8.4,
        "is_onboarding": 1,
        "fv": [0,0,0,1, 0,0,0,0, 0,0, 1,0,0, 0.84, 1,1,0,0, 0,0],
    },
    {
        "tmdb_id": 539, "title": "Psycho", "year": 1960,
        "director": "Alfred Hitchcock", "director_id": "hitchcock",
        "cast": ["Anthony Perkins", "Janet Leigh"],
        "genres": ["Horror", "Thriller"],
        "synopsis": "Une secrétaire en fuite s'arrête dans un motel isolé tenu par un étrange jeune homme.",
        "poster_url": "https://image.tmdb.org/t/p/w500/yz4QVqPx3h8hVSdMCd7ixNubCfv.jpg",
        "streaming_platforms": ["Peacock"],
        "avg_rating": 8.5,
        "is_onboarding": 0,
        "fv": [0,0,1,1, 0,0,0,0, 0,0, 1,0,0, 0.85, 1,0,1,0, 0,0],
    },
    {
        "tmdb_id": 346648, "title": "Hereditary", "year": 2018,
        "director": "Ari Aster", "director_id": "aster",
        "cast": ["Toni Collette", "Alex Wolff", "Gabriel Byrne"],
        "genres": ["Horror", "Drama"],
        "synopsis": "Une famille endeuillée découvre des secrets terrifiants liés à leur passé.",
        "poster_url": "https://image.tmdb.org/t/p/w500/4O1sPouIJBSTBqXJSyCqaxMd9Zw.jpg",
        "streaming_platforms": ["Prime Video"],
        "avg_rating": 7.3,
        "is_onboarding": 0,
        "fv": [0,1,0,1, 0,0,0,0, 0,0, 0,0,1, 0.73, 1,1,1,0, 0,0],
    },
    {
        "tmdb_id": 496243, "title": "Parasite", "year": 2019,
        "director": "Bong Joon-ho", "director_id": "bong",
        "cast": ["Kang-ho Song", "Sun-kyun Lee", "Yeo-jeong Jo"],
        "genres": ["Drama", "Thriller", "Crime"],
        "synopsis": "La famille Kim s'infiltre dans la vie de la riche famille Park.",
        "poster_url": "https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
        "streaming_platforms": ["Mubi"],
        "avg_rating": 8.5,
        "is_onboarding": 1,
        "fv": [0,1,1,0, 0,0,0,1, 0,0, 0,0,1, 0.85, 1,0,1,1, 0,1],
    },
    # ── Drama ─────────────────────────────────────────────────────────────
    {
        "tmdb_id": 264644, "title": "Room", "year": 2015,
        "director": "Lenny Abrahamson", "director_id": "abrahamson",
        "cast": ["Brie Larson", "Jacob Tremblay"],
        "genres": ["Drama", "Thriller"],
        "synopsis": "Une mère et son fils tentent de s'adapter après avoir été libérés d'une captivité.",
        "poster_url": "https://image.tmdb.org/t/p/w500/bOp0zKzsBJZKIHNhRVW0t2NxHSY.jpg",
        "streaming_platforms": ["Netflix"],
        "avg_rating": 8.1,
        "is_onboarding": 0,
        "fv": [0,1,1,0, 0,0,0,0, 0,0, 0,0,1, 0.81, 1,1,0,0, 0,0],
    },
    {
        "tmdb_id": 244786, "title": "Whiplash", "year": 2014,
        "director": "Damien Chazelle", "director_id": "chazelle",
        "cast": ["Miles Teller", "J.K. Simmons"],
        "genres": ["Drama", "Music"],
        "synopsis": "Un jeune batteur de jazz ambitieux est poussé à ses limites par un professeur tyrannique.",
        "poster_url": "https://image.tmdb.org/t/p/w500/7fn624j5lj3xTme2SgiLCeuedmO.jpg",
        "streaming_platforms": ["Netflix", "Prime Video"],
        "avg_rating": 8.5,
        "is_onboarding": 0,
        "fv": [0,1,0,0, 0,0,0,0, 0,0, 0,0,1, 0.85, 1,0,0,0, 0,0],
    },
    {
        "tmdb_id": 361743, "title": "Top Gun: Maverick", "year": 2022,
        "director": "Joseph Kosinski", "director_id": "kosinski",
        "cast": ["Tom Cruise", "Miles Teller", "Jennifer Connelly"],
        "genres": ["Action", "Drama"],
        "synopsis": "Maverick affronte ses démons tout en entraînant une nouvelle génération de pilotes.",
        "poster_url": "https://image.tmdb.org/t/p/w500/62HCnUTziyWcpDaBO2i1DX17ljH.jpg",
        "streaming_platforms": ["Paramount+", "Prime Video"],
        "avg_rating": 8.3,
        "is_onboarding": 0,
        "fv": [1,1,0,0, 0,0,0,0, 0,0, 0,0,1, 0.83, 0,0,0,0, 0,0],
    },
    {
        "tmdb_id": 120467, "title": "The Grand Budapest Hotel", "year": 2014,
        "director": "Wes Anderson", "director_id": "anderson_w",
        "cast": ["Ralph Fiennes", "Tony Revolori", "Saoirse Ronan"],
        "genres": ["Comedy", "Drama"],
        "synopsis": "Les aventures d'un concierge légendaire et de son jeune protégé dans un hôtel de luxe.",
        "poster_url": "https://image.tmdb.org/t/p/w500/eWdyYQreja6JGCzqHWXpWHDrrPo.jpg",
        "streaming_platforms": ["Disney+", "HBO Max"],
        "avg_rating": 8.1,
        "is_onboarding": 0,
        "fv": [0,1,0,0, 1,0,0,1, 0,0, 0,0,1, 0.81, 0,0,0,1, 0,0],
    },
    {
        "tmdb_id": 77338, "title": "The Artist", "year": 2011,
        "director": "Michel Hazanavicius", "director_id": "hazanavicius",
        "cast": ["Jean Dujardin", "Bérénice Bejo"],
        "genres": ["Comedy", "Drama", "Romance"],
        "synopsis": "Un acteur du muet voit sa carrière s'effondrer avec l'avènement du cinéma parlant.",
        "poster_url": "https://image.tmdb.org/t/p/w500/gTOAiP3eRhXGqxZwFcGhSDmSBYb.jpg",
        "streaming_platforms": ["Mubi"],
        "avg_rating": 7.9,
        "is_onboarding": 0,
        "fv": [0,1,0,0, 1,0,1,0, 0,0, 0,1,0, 0.79, 0,0,0,0, 0,1],
    },
    {
        "tmdb_id": 637, "title": "Life Is Beautiful", "year": 1997,
        "director": "Roberto Benigni", "director_id": "benigni",
        "cast": ["Roberto Benigni", "Nicoletta Braschi"],
        "genres": ["Drama", "Comedy", "Romance"],
        "synopsis": "Un père juif en Italie fasciste tente de protéger son fils dans un camp de concentration.",
        "poster_url": "https://image.tmdb.org/t/p/w500/74hLDKjD5aGYOotO6esUVaeISa2.jpg",
        "streaming_platforms": ["Netflix"],
        "avg_rating": 8.6,
        "is_onboarding": 0,
        "fv": [0,1,0,0, 1,0,1,0, 0,0, 1,0,0, 0.86, 1,0,0,0, 0,1],
    },
    # ── Action / Adventure ────────────────────────────────────────────────
    {
        "tmdb_id": 19404, "title": "Dilwale Dulhania Le Jayenge", "year": 1995,
        "director": "Aditya Chopra", "director_id": "chopra",
        "cast": ["Shah Rukh Khan", "Kajol"],
        "genres": ["Romance", "Drama"],
        "synopsis": "Deux jeunes Indiens de la diaspora tombent amoureux lors d'un voyage en Europe.",
        "poster_url": "https://image.tmdb.org/t/p/w500/2CAL2433ZeIihfX1Hb2139CX0pW.jpg",
        "streaming_platforms": ["Netflix"],
        "avg_rating": 8.1,
        "is_onboarding": 0,
        "fv": [0,1,0,0, 0,0,1,0, 0,0, 1,0,0, 0.81, 0,0,0,0, 0,1],
    },
    {
        "tmdb_id": 120, "title": "The Lord of the Rings: The Fellowship of the Ring", "year": 2001,
        "director": "Peter Jackson", "director_id": "jackson",
        "cast": ["Elijah Wood", "Ian McKellen", "Viggo Mortensen"],
        "genres": ["Action", "Drama", "Fantasy"],
        "synopsis": "Un jeune hobbit entreprend un voyage périlleux pour détruire un anneau maléfique.",
        "poster_url": "https://image.tmdb.org/t/p/w500/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg",
        "streaming_platforms": ["HBO Max"],
        "avg_rating": 8.8,
        "is_onboarding": 0,
        "fv": [1,1,0,0, 0,0,0,0, 0,0, 0,1,0, 0.88, 0,0,0,1, 0,0],
    },
    {
        "tmdb_id": 13916, "title": "Inglourious Basterds", "year": 2009,
        "director": "Quentin Tarantino", "director_id": "tarantino",
        "cast": ["Brad Pitt", "Christoph Waltz", "Mélanie Laurent"],
        "genres": ["Drama", "Action", "War"],
        "synopsis": "Plusieurs complots convergent pour assassiner Adolf Hitler dans la France occupée.",
        "poster_url": "https://image.tmdb.org/t/p/w500/7sfbEnaARXDDhKm0CZ7D7uc2sbo.jpg",
        "streaming_platforms": ["Netflix"],
        "avg_rating": 8.3,
        "is_onboarding": 0,
        "fv": [1,1,0,0, 0,0,0,0, 0,0, 0,1,0, 0.83, 1,0,1,1, 0,0],
    },
    {
        "tmdb_id": 101, "title": "Leon: The Professional", "year": 1994,
        "director": "Luc Besson", "director_id": "besson",
        "cast": ["Jean Reno", "Natalie Portman", "Gary Oldman"],
        "genres": ["Action", "Crime", "Drama"],
        "synopsis": "Un tueur à gages solitaire recueille une jeune fille dont la famille a été assassinée.",
        "poster_url": "https://image.tmdb.org/t/p/w500/yI6X2cCM5YPJtxMhUd3dPGqDAhw.jpg",
        "streaming_platforms": ["Prime Video"],
        "avg_rating": 8.5,
        "is_onboarding": 0,
        "fv": [1,1,0,0, 0,0,0,1, 0,0, 1,0,0, 0.85, 1,0,0,0, 0,1],
    },
    {
        "tmdb_id": 637649, "title": "Mad Max: Fury Road", "year": 2015,
        "director": "George Miller", "director_id": "miller_g",
        "cast": ["Tom Hardy", "Charlize Theron"],
        "genres": ["Action", "SciFi"],
        "synopsis": "Dans un monde post-apocalyptique, un ancien flic aide une impératrice à fuir un tyran.",
        "poster_url": "https://image.tmdb.org/t/p/w500/8tZYtuWezp8JbcsvHYO0O46tFbo.jpg",
        "streaming_platforms": ["HBO Max"],
        "avg_rating": 8.1,
        "is_onboarding": 0,
        "fv": [1,0,0,0, 0,1,0,0, 0,0, 0,0,1, 0.81, 1,0,0,0, 0,0],
    },
    # ── Comedy ────────────────────────────────────────────────────────────
    {
        "tmdb_id": 19, "title": "Amélie", "year": 2001,
        "director": "Jean-Pierre Jeunet", "director_id": "jeunet",
        "cast": ["Audrey Tautou", "Mathieu Kassovitz"],
        "genres": ["Comedy", "Romance"],
        "synopsis": "Une jeune femme rêveuse décide d'améliorer la vie des gens qui l'entourent.",
        "poster_url": "https://image.tmdb.org/t/p/w500/mMtucybCbBemqta6OLe0G8gv0Ww.jpg",
        "streaming_platforms": ["Mubi", "Prime Video"],
        "avg_rating": 8.3,
        "is_onboarding": 0,
        "fv": [0,0,0,0, 1,0,1,0, 0,0, 0,1,0, 0.83, 0,0,0,0, 0,1],
    },
    {
        "tmdb_id": 68718, "title": "Django Unchained", "year": 2012,
        "director": "Quentin Tarantino", "director_id": "tarantino",
        "cast": ["Jamie Foxx", "Christoph Waltz", "Leonardo DiCaprio"],
        "genres": ["Drama", "Action", "Western"],
        "synopsis": "Un esclave affranchi et un chasseur de primes partent à la recherche de la femme de l'un d'eux.",
        "poster_url": "https://image.tmdb.org/t/p/w500/7oWY8VDWW7thTzWh3OKYRkWUlD5.jpg",
        "streaming_platforms": ["Netflix"],
        "avg_rating": 8.4,
        "is_onboarding": 0,
        "fv": [1,1,0,0, 0,0,0,0, 0,0, 0,0,1, 0.84, 1,0,0,0, 0,0],
    },
    {
        "tmdb_id": 1817, "title": "There Will Be Blood", "year": 2007,
        "director": "Paul Thomas Anderson", "director_id": "pta",
        "cast": ["Daniel Day-Lewis", "Paul Dano"],
        "genres": ["Drama"],
        "synopsis": "L'ascension d'un prospecteur pétrolier implacable dans la Californie du début du XXe siècle.",
        "poster_url": "https://image.tmdb.org/t/p/w500/fa0RDkAlCec0STeMNAhPaF89q6U.jpg",
        "streaming_platforms": ["Mubi"],
        "avg_rating": 8.2,
        "is_onboarding": 0,
        "fv": [0,1,0,0, 0,0,0,0, 0,0, 0,1,0, 0.82, 1,1,0,0, 0,0],
    },
    {
        "tmdb_id": 489, "title": "Good Will Hunting", "year": 1997,
        "director": "Gus Van Sant", "director_id": "vansant",
        "cast": ["Matt Damon", "Robin Williams", "Ben Affleck"],
        "genres": ["Drama", "Romance"],
        "synopsis": "Un jeune génie travaillant comme concierge du MIT est aidé par un psychologue compatissant.",
        "poster_url": "https://image.tmdb.org/t/p/w500/bABCBKYBK7A5G1x0FzoeoNfuj2.jpg",
        "streaming_platforms": ["Netflix"],
        "avg_rating": 8.3,
        "is_onboarding": 0,
        "fv": [0,1,0,0, 0,0,1,0, 0,0, 1,0,0, 0.83, 0,0,0,0, 0,0],
    },
    {
        "tmdb_id": 566525, "title": "Shang-Chi and the Legend of the Ten Rings", "year": 2021,
        "director": "Destin Daniel Cretton", "director_id": "cretton",
        "cast": ["Simu Liu", "Tony Leung", "Awkwafina"],
        "genres": ["Action", "Fantasy"],
        "synopsis": "Un homme est entraîné dans le monde de la Ten Rings, une organisation secrète.",
        "poster_url": "https://image.tmdb.org/t/p/w500/1BIoJGKbXjdFDAqUEiA2VHqkK1Z.jpg",
        "streaming_platforms": ["Disney+"],
        "avg_rating": 7.4,
        "is_onboarding": 0,
        "fv": [1,0,0,0, 0,0,0,0, 0,0, 0,0,1, 0.74, 0,0,0,0, 0,0],
    },
    {
        "tmdb_id": 724089, "title": "Gabriel's Inferno", "year": 2020,
        "director": "Tosca Musk", "director_id": "musk_t",
        "cast": ["Giulio Berruti", "Melanie Zanetti"],
        "genres": ["Romance", "Drama"],
        "synopsis": "Un professeur de Dante et son étudiante vivent une histoire d'amour interdite.",
        "poster_url": "https://image.tmdb.org/t/p/w500/oyG9TL7FcRP4EZ9Vid6uKzwdndz.jpg",
        "streaming_platforms": ["Prime Video"],
        "avg_rating": 7.0,
        "is_onboarding": 0,
        "fv": [0,1,0,0, 0,0,1,0, 0,0, 0,0,1, 0.70, 0,0,0,0, 0,0],
    },
    # ── Foreign / Art House ───────────────────────────────────────────────
    {
        "tmdb_id": 129, "title": "Spirited Away", "year": 2001,
        "director": "Hayao Miyazaki", "director_id": "miyazaki",
        "cast": ["Daveigh Chase", "Suzanne Pleshette"],
        "genres": ["Animation", "Fantasy", "Drama"],
        "synopsis": "Une jeune fille est entraînée dans un monde fantastique après que ses parents sont transformés en cochons.",
        "poster_url": "https://image.tmdb.org/t/p/w500/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg",
        "streaming_platforms": ["Netflix"],
        "avg_rating": 8.6,
        "is_onboarding": 0,
        "fv": [0,1,0,0, 0,0,0,0, 1,0, 0,1,0, 0.86, 0,0,0,0, 0,1],
    },
    {
        "tmdb_id": 429617, "title": "Spider-Man: Into the Spider-Verse", "year": 2018,
        "director": "Bob Persichetti", "director_id": "persichetti",
        "cast": ["Shameik Moore", "Jake Johnson"],
        "genres": ["Animation", "Action", "SciFi"],
        "synopsis": "Miles Morales devient Spider-Man et rencontre des Spider-Men d'autres dimensions.",
        "poster_url": "https://image.tmdb.org/t/p/w500/iiZZdoQBEYBv6id8su7ImL0oCbD.jpg",
        "streaming_platforms": ["Netflix"],
        "avg_rating": 8.4,
        "is_onboarding": 0,
        "fv": [1,0,0,0, 0,1,0,0, 1,0, 0,0,1, 0.84, 0,0,1,1, 0,0],
    },
    {
        "tmdb_id": 508442, "title": "Soul", "year": 2020,
        "director": "Pete Docter", "director_id": "docter",
        "cast": ["Jamie Foxx", "Tina Fey"],
        "genres": ["Animation", "Comedy", "Drama"],
        "synopsis": "Un musicien de jazz se retrouve dans le monde des âmes avant de naître.",
        "poster_url": "https://image.tmdb.org/t/p/w500/hm58Jw4Lw8OIeECIq5qyPYhAeRJ.jpg",
        "streaming_platforms": ["Disney+"],
        "avg_rating": 8.1,
        "is_onboarding": 0,
        "fv": [0,1,0,0, 1,0,0,0, 1,0, 0,0,1, 0.81, 0,0,1,0, 0,0],
    },
    {
        "tmdb_id": 264660, "title": "Ex Machina", "year": 2014,
        "director": "Alex Garland", "director_id": "garland",
        "cast": ["Domhnall Gleeson", "Alicia Vikander", "Oscar Isaac"],
        "genres": ["SciFi", "Thriller", "Drama"],
        "synopsis": "Un programmeur est sélectionné pour évaluer les capacités d'une IA à forme humaine.",
        "poster_url": "https://image.tmdb.org/t/p/w500/btpFaZFg3bwzKzGqOuGlCDtN8Gg.jpg",
        "streaming_platforms": ["Prime Video", "Netflix"],
        "avg_rating": 7.7,
        "is_onboarding": 0,
        "fv": [0,1,1,0, 0,1,0,0, 0,0, 0,0,1, 0.77, 1,1,1,0, 0,0],
    },
    {
        "tmdb_id": 299536, "title": "Avengers: Infinity War", "year": 2018,
        "director": "Anthony Russo", "director_id": "russo_a",
        "cast": ["Robert Downey Jr.", "Chris Evans", "Josh Brolin"],
        "genres": ["Action", "SciFi"],
        "synopsis": "Les Avengers s'unissent pour empêcher Thanos de rassembler les Pierres de l'Infini.",
        "poster_url": "https://image.tmdb.org/t/p/w500/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg",
        "streaming_platforms": ["Disney+"],
        "avg_rating": 8.4,
        "is_onboarding": 0,
        "fv": [1,0,0,0, 0,1,0,0, 0,0, 0,0,1, 0.84, 1,0,1,1, 0,0],
    },
    {
        "tmdb_id": 313369, "title": "La La Land", "year": 2016,
        "director": "Damien Chazelle", "director_id": "chazelle",
        "cast": ["Ryan Gosling", "Emma Stone"],
        "genres": ["Drama", "Romance", "Music"],
        "synopsis": "Un pianiste de jazz et une aspirante actrice tombent amoureux à Los Angeles.",
        "poster_url": "https://image.tmdb.org/t/p/w500/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg",
        "streaming_platforms": ["Netflix"],
        "avg_rating": 8.0,
        "is_onboarding": 0,
        "fv": [0,1,0,0, 0,0,1,0, 0,0, 0,0,1, 0.80, 0,0,0,0, 0,0],
    },
    {
        "tmdb_id": 475557, "title": "Joker", "year": 2019,
        "director": "Todd Phillips", "director_id": "phillips",
        "cast": ["Joaquin Phoenix", "Robert De Niro"],
        "genres": ["Crime", "Drama", "Thriller"],
        "synopsis": "L'origine d'Arthur Fleck, un comédien raté qui sombre dans la folie et devient le Joker.",
        "poster_url": "https://image.tmdb.org/t/p/w500/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg",
        "streaming_platforms": ["HBO Max"],
        "avg_rating": 8.4,
        "is_onboarding": 0,
        "fv": [0,1,1,0, 0,0,0,1, 0,0, 0,0,1, 0.84, 1,1,0,0, 1,0],
    },
    {
        "tmdb_id": 901362, "title": "Trolls Band Together", "year": 2023,
        "director": "Walt Dohrn", "director_id": "dohrn",
        "cast": ["Anna Kendrick", "Justin Timberlake"],
        "genres": ["Animation", "Comedy", "Music"],
        "synopsis": "Poppy aide Branch à retrouver ses frères boy band pour sauver leur petite sœur.",
        "poster_url": "https://image.tmdb.org/t/p/w500/bkpPTZUdq31UGDovmszsg2CchiI.jpg",
        "streaming_platforms": ["Netflix", "Peacock"],
        "avg_rating": 5.9,
        "is_onboarding": 0,
        "fv": [0,0,0,0, 1,0,0,0, 1,0, 0,0,1, 0.59, 0,0,0,0, 0,0],
    },
    {
        "tmdb_id": 346, "title": "Seven Samurai", "year": 1954,
        "director": "Akira Kurosawa", "director_id": "kurosawa",
        "cast": ["Toshiro Mifune", "Takashi Shimura"],
        "genres": ["Action", "Drama"],
        "synopsis": "Un village de paysans engage sept samouraïs pour les protéger contre des bandits.",
        "poster_url": "https://image.tmdb.org/t/p/w500/8OKmBV5BUFzmozIC3pPWKHy17kx.jpg",
        "streaming_platforms": ["Criterion", "Mubi"],
        "avg_rating": 8.7,
        "is_onboarding": 0,
        "fv": [1,1,0,0, 0,0,0,0, 0,0, 1,0,0, 0.87, 0,1,0,1, 0,1],
    },
    {
        "tmdb_id": 240, "title": "The Godfather Part II", "year": 1974,
        "director": "Francis Ford Coppola", "director_id": "coppola",
        "cast": ["Al Pacino", "Robert De Niro", "Robert Duvall"],
        "genres": ["Crime", "Drama"],
        "synopsis": "L'empire de Michael Corleone s'étend alors que des flashbacks montrent la jeunesse de Vito.",
        "poster_url": "https://image.tmdb.org/t/p/w500/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg",
        "streaming_platforms": ["Prime Video", "Paramount+"],
        "avg_rating": 9.0,
        "is_onboarding": 0,
        "fv": [0,1,0,0, 0,0,0,1, 0,0, 1,0,0, 0.90, 1,1,0,1, 0,0],
    },
    {
        "tmdb_id": 598, "title": "City of God", "year": 2002,
        "director": "Fernando Meirelles", "director_id": "meirelles",
        "cast": ["Alexandre Rodrigues", "Leandro Firmino"],
        "genres": ["Crime", "Drama"],
        "synopsis": "Deux jeunes hommes grandissent dans les favelas de Rio de Janeiro des années 60-80.",
        "poster_url": "https://image.tmdb.org/t/p/w500/k7eYdWvhYQyRQoU2TB2A2Xu2grZ.jpg",
        "streaming_platforms": ["Netflix"],
        "avg_rating": 8.6,
        "is_onboarding": 0,
        "fv": [0,1,0,0, 0,0,0,1, 0,0, 0,1,0, 0.86, 1,0,0,0, 0,1],
    },
    {
        "tmdb_id": 762, "title": "Monty Python and the Holy Grail", "year": 1975,
        "director": "Terry Gilliam", "director_id": "gilliam",
        "cast": ["Graham Chapman", "John Cleese", "Terry Gilliam"],
        "genres": ["Comedy"],
        "synopsis": "Le Roi Arthur et ses chevaliers partent en quête du Saint Graal.",
        "poster_url": "https://image.tmdb.org/t/p/w500/sGyllguekBSFqpUMhtpFkDpNYmQ.jpg",
        "streaming_platforms": ["Netflix"],
        "avg_rating": 8.2,
        "is_onboarding": 0,
        "fv": [0,0,0,0, 1,0,0,0, 0,0, 1,0,0, 0.82, 0,0,0,1, 0,0],
    },
    {
        "tmdb_id": 37724, "title": "Skyfall", "year": 2012,
        "director": "Sam Mendes", "director_id": "mendes",
        "cast": ["Daniel Craig", "Judi Dench", "Javier Bardem"],
        "genres": ["Action", "Thriller"],
        "synopsis": "James Bond affronte un ancien agent du MI6 qui cherche à se venger.",
        "poster_url": "https://image.tmdb.org/t/p/w500/dyFGMzCNY1vE8I3S5qFrLjBqGq4.jpg",
        "streaming_platforms": ["Netflix", "Prime Video"],
        "avg_rating": 7.8,
        "is_onboarding": 0,
        "fv": [1,0,1,0, 0,0,0,0, 0,0, 0,0,1, 0.78, 0,0,1,0, 0,0],
    },
    {
        "tmdb_id": 280, "title": "Terminator 2: Judgment Day", "year": 1991,
        "director": "James Cameron", "director_id": "cameron",
        "cast": ["Arnold Schwarzenegger", "Linda Hamilton", "Edward Furlong"],
        "genres": ["Action", "SciFi"],
        "synopsis": "Un Terminator reprogrammé protège le jeune John Connor d'un robot du futur plus avancé.",
        "poster_url": "https://image.tmdb.org/t/p/w500/5M0j0B18abtBI5gi2RhfjjurTqb.jpg",
        "streaming_platforms": ["Netflix"],
        "avg_rating": 8.6,
        "is_onboarding": 0,
        "fv": [1,0,0,0, 0,1,0,0, 0,0, 1,0,0, 0.86, 1,0,1,0, 0,0],
    },
    {
        "tmdb_id": 11, "title": "Star Wars: A New Hope", "year": 1977,
        "director": "George Lucas", "director_id": "lucas",
        "cast": ["Mark Hamill", "Harrison Ford", "Carrie Fisher"],
        "genres": ["Action", "SciFi", "Fantasy"],
        "synopsis": "Un jeune fermier rejoint la Rébellion galactique contre l'Empire tyrannique.",
        "poster_url": "https://image.tmdb.org/t/p/w500/6FfCtAuVAW8XJjZ7eWeLibRLWTw.jpg",
        "streaming_platforms": ["Disney+"],
        "avg_rating": 8.6,
        "is_onboarding": 0,
        "fv": [1,0,0,0, 0,1,0,0, 0,0, 1,0,0, 0.86, 0,0,0,1, 0,0],
    },
    {
        "tmdb_id": 23272, "title": "Into the Wild", "year": 2007,
        "director": "Sean Penn", "director_id": "penn",
        "cast": ["Emile Hirsch", "Marcia Gay Harden", "William Hurt"],
        "genres": ["Drama", "Adventure"],
        "synopsis": "Après avoir donné ses économies à une association, un jeune diplômé part seul en Alaska.",
        "poster_url": "https://image.tmdb.org/t/p/w500/wBthfNBLQOC3szVKPYsemysPFJv.jpg",
        "streaming_platforms": ["Netflix"],
        "avg_rating": 8.1,
        "is_onboarding": 0,
        "fv": [0,1,0,0, 0,0,0,0, 0,0, 0,1,0, 0.81, 0,1,0,0, 1,0],
    },
    {
        "tmdb_id": 372058, "title": "Your Name", "year": 2016,
        "director": "Makoto Shinkai", "director_id": "shinkai",
        "cast": ["Ryunosuke Kamiki", "Mone Kamishiraishi"],
        "genres": ["Animation", "Drama", "Romance"],
        "synopsis": "Deux lycéens se retrouvent mystérieusement à échanger leurs corps.",
        "poster_url": "https://image.tmdb.org/t/p/w500/q719jXXEzOoYaps6babgKnONONX.jpg",
        "streaming_platforms": ["Netflix"],
        "avg_rating": 8.4,
        "is_onboarding": 0,
        "fv": [0,1,0,0, 0,0,1,0, 1,0, 0,0,1, 0.84, 0,0,1,0, 0,1],
    },
    {
        "tmdb_id": 598650, "title": "The Batman", "year": 2022,
        "director": "Matt Reeves", "director_id": "reeves",
        "cast": ["Robert Pattinson", "Zoë Kravitz", "Paul Dano"],
        "genres": ["Action", "Crime", "Thriller"],
        "synopsis": "Batman démasque la corruption de Gotham alors qu'il pourchasse un tueur en série.",
        "poster_url": "https://image.tmdb.org/t/p/w500/74xTEgt7R36Fpooo50r9T25onhq.jpg",
        "streaming_platforms": ["HBO Max"],
        "avg_rating": 7.8,
        "is_onboarding": 0,
        "fv": [1,0,1,0, 0,0,0,1, 0,0, 0,0,1, 0.78, 1,1,1,0, 0,0],
    },
    {
        "tmdb_id": 539681, "title": "Oppenheimer", "year": 2023,
        "director": "Christopher Nolan", "director_id": "nolan",
        "cast": ["Cillian Murphy", "Emily Blunt", "Matt Damon"],
        "genres": ["Drama", "History"],
        "synopsis": "La vie du physicien J. Robert Oppenheimer qui a dirigé le Projet Manhattan.",
        "poster_url": "https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
        "streaming_platforms": ["Peacock"],
        "avg_rating": 8.3,
        "is_onboarding": 0,
        "fv": [0,1,0,0, 0,0,0,0, 0,0, 0,0,1, 0.83, 1,1,0,1, 1,0],
    },
    {
        "tmdb_id": 545611, "title": "Everything Everywhere All at Once", "year": 2022,
        "director": "Daniel Kwan", "director_id": "daniels",
        "cast": ["Michelle Yeoh", "Stephanie Hsu", "Ke Huy Quan"],
        "genres": ["SciFi", "Comedy", "Drama"],
        "synopsis": "Une femme découvre qu'elle seule peut sauver le multivers en explorant d'autres vies.",
        "poster_url": "https://image.tmdb.org/t/p/w500/w3LxiVYdWWRvEVdn5RYq6jIqkb1.jpg",
        "streaming_platforms": ["Prime Video", "Mubi"],
        "avg_rating": 7.8,
        "is_onboarding": 0,
        "fv": [0,1,0,0, 1,1,0,0, 0,0, 0,0,1, 0.78, 0,0,1,0, 0,0],
    },
    {
        "tmdb_id": 76341, "title": "Mad Max: Fury Road", "year": 2015,
        "director": "George Miller", "director_id": "miller_g",
        "cast": ["Tom Hardy", "Charlize Theron", "Nicholas Hoult"],
        "genres": ["Action", "SciFi"],
        "synopsis": "Dans un désert post-apocalyptique, Max aide Furiosa à libérer des esclaves.",
        "poster_url": "https://image.tmdb.org/t/p/w500/8tZYtuWezp8JbcsvHYO0O46tFbo.jpg",
        "streaming_platforms": ["Netflix", "HBO Max"],
        "avg_rating": 8.1,
        "is_onboarding": 0,
        "fv": [1,0,0,0, 0,1,0,0, 0,0, 0,0,1, 0.81, 1,0,0,0, 0,0],
    },
]
# fmt: on

VECTOR_DIM = 20


def normalize(v: list) -> list:
    norm = math.sqrt(sum(x * x for x in v))
    if norm == 0:
        return v
    return [x / norm for x in v]


async def seed():
    await create_tables()
    async with aiosqlite.connect(DB_PATH) as db:
        # Check if already seeded
        cursor = await db.execute("SELECT COUNT(*) FROM movies")
        count = (await cursor.fetchone())[0]
        if count > 0:
            print(f"Database already seeded with {count} movies. Skipping.")
            return

        for m in MOVIES:
            fv = normalize(m["fv"])
            await db.execute(
                """INSERT INTO movies
                   (tmdb_id, title, year, director, director_id, cast, genres,
                    synopsis, poster_url, streaming_platforms, avg_rating,
                    feature_vector, is_onboarding)
                   VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)""",
                (
                    m["tmdb_id"],
                    m["title"],
                    m["year"],
                    m["director"],
                    m["director_id"],
                    json.dumps(m["cast"]),
                    json.dumps(m["genres"]),
                    m["synopsis"],
                    m["poster_url"],
                    json.dumps(m["streaming_platforms"]),
                    m["avg_rating"],
                    json.dumps(fv),
                    m["is_onboarding"],
                ),
            )
        await db.commit()
        print(f"Seeded {len(MOVIES)} movies into the database.")


if __name__ == "__main__":
    asyncio.run(seed())
